// GENERATED by scripts/gen-i18n.py from i18n/strings.json — do not edit by hand.
//
// Exposes `window.i18n`: the string table plus the small runtime the pages share —
// locale negotiation, persistence, {placeholder} interpolation and localized language
// names. No framework, no build step at page load; the file is the bundle.
(function () {
  var DATA = {
  "locales": [
    {
      "code": "en",
      "endonym": "English",
      "dir": "ltr"
    },
    {
      "code": "es",
      "endonym": "Español",
      "dir": "ltr"
    },
    {
      "code": "fr",
      "endonym": "Français",
      "dir": "ltr"
    },
    {
      "code": "de",
      "endonym": "Deutsch",
      "dir": "ltr"
    },
    {
      "code": "pt",
      "endonym": "Português",
      "dir": "ltr"
    },
    {
      "code": "it",
      "endonym": "Italiano",
      "dir": "ltr"
    },
    {
      "code": "nl",
      "endonym": "Nederlands",
      "dir": "ltr"
    },
    {
      "code": "ru",
      "endonym": "Русский",
      "dir": "ltr"
    },
    {
      "code": "ja",
      "endonym": "日本語",
      "dir": "ltr"
    },
    {
      "code": "zh-Hans",
      "endonym": "简体中文",
      "dir": "ltr"
    },
    {
      "code": "ko",
      "endonym": "한국어",
      "dir": "ltr"
    },
    {
      "code": "ar",
      "endonym": "العربية",
      "dir": "rtl"
    }
  ],
  "strings": {
    "app.tagline": {
      "en": "Dictionary with deep etymology",
      "es": "Diccionario con etimología profunda",
      "fr": "Dictionnaire avec une étymologie approfondie",
      "de": "Wörterbuch mit tiefgehender Etymologie",
      "pt": "Dicionário com etimologia profunda",
      "it": "Dizionario con etimologia approfondita",
      "nl": "Woordenboek met diepgaande etymologie",
      "ru": "Словарь с глубокой этимологией",
      "ja": "語源をたどる辞書",
      "zh-Hans": "带有深度词源的词典",
      "ko": "깊이 있는 어원 사전",
      "ar": "قاموس مع أصول متعمقة للكلمات"
    },
    "ui.language": {
      "en": "Language",
      "es": "Idioma",
      "fr": "Langue",
      "de": "Sprache",
      "pt": "Idioma",
      "it": "Lingua",
      "nl": "Taal",
      "ru": "Язык",
      "ja": "言語",
      "zh-Hans": "语言",
      "ko": "언어",
      "ar": "اللغة"
    },
    "ui.privacy": {
      "en": "Privacy",
      "es": "Privacidad",
      "fr": "Confidentialité",
      "de": "Datenschutz",
      "pt": "Privacidade",
      "it": "Privacy",
      "nl": "Privacy",
      "ru": "Конфиденциальность",
      "ja": "プライバシー",
      "zh-Hans": "隐私",
      "ko": "개인정보",
      "ar": "الخصوصية"
    },
    "landing.title": {
      "en": "Wordroot — dictionary with deep etymology",
      "es": "Wordroot — diccionario con etimología profunda",
      "fr": "Wordroot — dictionnaire avec étymologie approfondie",
      "de": "Wordroot — Wörterbuch mit tiefgehender Etymologie",
      "pt": "Wordroot — dicionário com etimologia profunda",
      "it": "Wordroot — dizionario con etimologia approfondita",
      "nl": "Wordroot — woordenboek met diepgaande etymologie",
      "ru": "Wordroot — словарь с глубокой этимологией",
      "ja": "Wordroot — 語源をたどる辞書",
      "zh-Hans": "Wordroot — 深度词源词典",
      "ko": "Wordroot — 깊이 있는 어원 사전",
      "ar": "Wordroot — قاموس مع أصول متعمقة للكلمات"
    },
    "landing.description": {
      "en": "Trace any word back through Latin, Greek, and Proto-Indo-European with an interactive etymology tree and cognate links.",
      "es": "Rastrea cualquier palabra a través del latín, el griego y el protoindoeuropeo con un árbol etimológico interactivo y enlaces a cognados.",
      "fr": "Remontez l’origine de n’importe quel mot à travers le latin, le grec et l’indo-européen commun grâce à un arbre étymologique interactif et des liens vers les mots apparentés.",
      "de": "Verfolge jedes Wort über das Lateinische, Griechische und Urindogermanische zurück – mit einem interaktiven Etymologiebaum und Verweisen auf verwandte Wörter.",
      "pt": "Rastreie qualquer palavra através do latim, do grego e do proto-indo-europeu com uma árvore etimológica interativa e ligações a cognatos.",
      "it": "Risali all’origine di qualsiasi parola attraverso latino, greco e proto-indoeuropeo con un albero etimologico interattivo e collegamenti ai cognati.",
      "nl": "Volg elk woord terug via het Latijn, het Grieks en het Proto-Indo-Europees met een interactieve etymologieboom en verwante woorden.",
      "ru": "Проследите происхождение любого слова через латынь, греческий и праиндоевропейский с помощью интерактивного дерева этимологии и ссылок на родственные слова.",
      "ja": "インタラクティブな語源ツリーと同根語リンクで、どんな単語もラテン語・ギリシャ語・印欧祖語までさかのぼれます。",
      "zh-Hans": "通过交互式词源树和同源词链接，将任何单词追溯到拉丁语、希腊语和原始印欧语。",
      "ko": "인터랙티브 어원 트리와 동족어 링크로 어떤 단어든 라틴어, 그리스어, 인도유럽조어까지 거슬러 올라가 보세요.",
      "ar": "تتبّع أصل أي كلمة عبر اللاتينية واليونانية والهندية الأوروبية البدائية، بشجرة اشتقاق تفاعلية وروابط للكلمات المشتركة الجذر."
    },
    "landing.hero.sub": {
      "en": "A clean dictionary that shows you where words actually come from — traced back through Latin, Greek, and Proto-Indo-European.",
      "es": "Un diccionario limpio que te muestra de dónde vienen realmente las palabras, rastreadas hasta el latín, el griego y el protoindoeuropeo.",
      "fr": "Un dictionnaire épuré qui montre d’où viennent vraiment les mots, jusqu’au latin, au grec et à l’indo-européen commun.",
      "de": "Ein aufgeräumtes Wörterbuch, das zeigt, woher Wörter wirklich kommen – zurückverfolgt bis ins Lateinische, Griechische und Urindogermanische.",
      "pt": "Um dicionário limpo que mostra de onde as palavras realmente vêm, rastreadas até ao latim, ao grego e ao proto-indo-europeu.",
      "it": "Un dizionario essenziale che mostra da dove vengono davvero le parole, risalendo al latino, al greco e al proto-indoeuropeo.",
      "nl": "Een overzichtelijk woordenboek dat laat zien waar woorden echt vandaan komen — terug tot het Latijn, het Grieks en het Proto-Indo-Europees.",
      "ru": "Понятный словарь, который показывает, откуда на самом деле берутся слова — вплоть до латыни, греческого и праиндоевропейского.",
      "ja": "単語が本当はどこから来たのかを示す、すっきりした辞書。ラテン語・ギリシャ語・印欧祖語までさかのぼります。",
      "zh-Hans": "一款简洁的词典，告诉你单词真正的来处——一路追溯到拉丁语、希腊语和原始印欧语。",
      "ko": "단어가 실제로 어디에서 왔는지 보여 주는 깔끔한 사전. 라틴어, 그리스어, 인도유럽조어까지 거슬러 올라갑니다.",
      "ar": "قاموس أنيق يكشف من أين أتت الكلمات فعلاً — رجوعاً إلى اللاتينية واليونانية والهندية الأوروبية البدائية."
    },
    "landing.cta.open": {
      "en": "Open Wordroot",
      "es": "Abrir Wordroot",
      "fr": "Ouvrir Wordroot",
      "de": "Wordroot öffnen",
      "pt": "Abrir o Wordroot",
      "it": "Apri Wordroot",
      "nl": "Wordroot openen",
      "ru": "Открыть Wordroot",
      "ja": "Wordroot を開く",
      "zh-Hans": "打开 Wordroot",
      "ko": "Wordroot 열기",
      "ar": "افتح Wordroot"
    },
    "landing.cta.source": {
      "en": "Source",
      "es": "Código",
      "fr": "Code source",
      "de": "Quellcode",
      "pt": "Código",
      "it": "Codice",
      "nl": "Broncode",
      "ru": "Исходный код",
      "ja": "ソース",
      "zh-Hans": "源码",
      "ko": "소스",
      "ar": "الشيفرة"
    },
    "landing.features.title": {
      "en": "Every word has a history. Wordroot shows it.",
      "es": "Cada palabra tiene una historia. Wordroot te la muestra.",
      "fr": "Chaque mot a une histoire. Wordroot vous la montre.",
      "de": "Jedes Wort hat eine Geschichte. Wordroot zeigt sie.",
      "pt": "Cada palavra tem uma história. O Wordroot mostra-a.",
      "it": "Ogni parola ha una storia. Wordroot te la mostra.",
      "nl": "Elk woord heeft een geschiedenis. Wordroot laat die zien.",
      "ru": "У каждого слова есть история. Wordroot её показывает.",
      "ja": "すべての単語に歴史がある。Wordroot はそれを見せます。",
      "zh-Hans": "每个单词都有历史。Wordroot 让你看见。",
      "ko": "모든 단어에는 역사가 있습니다. Wordroot가 보여 줍니다.",
      "ar": "لكل كلمة تاريخ. وWordroot يُظهره."
    },
    "landing.f1.title": {
      "en": "Interactive etymology tree",
      "es": "Árbol etimológico interactivo",
      "fr": "Arbre étymologique interactif",
      "de": "Interaktiver Etymologiebaum",
      "pt": "Árvore etimológica interativa",
      "it": "Albero etimologico interattivo",
      "nl": "Interactieve etymologieboom",
      "ru": "Интерактивное дерево этимологии",
      "ja": "インタラクティブな語源ツリー",
      "zh-Hans": "交互式词源树",
      "ko": "인터랙티브 어원 트리",
      "ar": "شجرة اشتقاق تفاعلية"
    },
    "landing.f1.body": {
      "en": "Follow a word backwards through each ancestor language, one branch at a time.",
      "es": "Sigue una palabra hacia atrás por cada lengua antecesora, rama a rama.",
      "fr": "Remontez un mot langue ancestrale par langue ancestrale, branche après branche.",
      "de": "Verfolge ein Wort Zweig für Zweig durch jede Vorgängersprache zurück.",
      "pt": "Siga uma palavra para trás por cada língua ancestral, um ramo de cada vez.",
      "it": "Segui una parola a ritroso attraverso ogni lingua antenata, un ramo alla volta.",
      "nl": "Volg een woord terug door elke voorouderlijke taal, tak voor tak.",
      "ru": "Проследите слово назад через каждый язык-предок, ветвь за ветвью.",
      "ja": "祖先言語をひとつずつ、枝をたどって単語をさかのぼる。",
      "zh-Hans": "沿着每一门祖先语言，一枝一枝地回溯一个单词。",
      "ko": "조상 언어를 하나씩, 가지를 따라 단어를 거슬러 올라갑니다.",
      "ar": "تتبّع الكلمة رجوعاً عبر كل لغة سلف، فرعاً تلو الآخر."
    },
    "landing.f2.title": {
      "en": "Real cognate links",
      "es": "Cognados de verdad",
      "fr": "De vrais liens entre mots apparentés",
      "de": "Echte Verweise auf verwandte Wörter",
      "pt": "Ligações reais a cognatos",
      "it": "Veri collegamenti tra cognati",
      "nl": "Echte links naar verwante woorden",
      "ru": "Настоящие связи родственных слов",
      "ja": "本物の同根語リンク",
      "zh-Hans": "真实的同源词链接",
      "ko": "실제 동족어 링크",
      "ar": "روابط حقيقية للكلمات المشتركة الجذر"
    },
    "landing.f2.body": {
      "en": "See the related words in other languages that share the same root.",
      "es": "Descubre las palabras de otras lenguas que comparten la misma raíz.",
      "fr": "Découvrez les mots d’autres langues qui partagent la même racine.",
      "de": "Sieh die Wörter anderer Sprachen, die dieselbe Wurzel teilen.",
      "pt": "Veja as palavras de outras línguas que partilham a mesma raiz.",
      "it": "Scopri le parole di altre lingue che condividono la stessa radice.",
      "nl": "Bekijk de woorden in andere talen die dezelfde wortel delen.",
      "ru": "Смотрите слова других языков с тем же корнем.",
      "ja": "同じ語根を共有する他言語の単語を見つけられます。",
      "zh-Hans": "看到其他语言中共享同一词根的相关词。",
      "ko": "같은 어근을 공유하는 다른 언어의 단어를 확인하세요.",
      "ar": "اطّلع على كلمات لغات أخرى تشترك في الجذر نفسه."
    },
    "landing.f3.title": {
      "en": "Live Wiktionary data",
      "es": "Datos en vivo de Wikcionario",
      "fr": "Données du Wiktionnaire en direct",
      "de": "Live-Daten aus dem Wiktionary",
      "pt": "Dados do Wikcionário em tempo real",
      "it": "Dati del Wikizionario in tempo reale",
      "nl": "Live gegevens uit WikiWoordenboek",
      "ru": "Актуальные данные Викисловаря",
      "ja": "ウィクショナリーのライブデータ",
      "zh-Hans": "实时维基词典数据",
      "ko": "실시간 위키낱말사전 데이터",
      "ar": "بيانات ويكاموس حيّة"
    },
    "landing.f3.body": {
      "en": "Definitions and etymologies come from Wiktionary, parsed into a proper graph.",
      "es": "Las definiciones y etimologías vienen de Wikcionario, convertidas en un grafo real.",
      "fr": "Les définitions et étymologies viennent du Wiktionnaire, converties en un véritable graphe.",
      "de": "Definitionen und Etymologien stammen aus dem Wiktionary und werden in einen echten Graphen überführt.",
      "pt": "As definições e etimologias vêm do Wikcionário, convertidas num grafo a sério.",
      "it": "Definizioni ed etimologie vengono dal Wikizionario, trasformate in un vero grafo.",
      "nl": "Definities en etymologieën komen uit WikiWoordenboek, omgezet in een echte graaf.",
      "ru": "Определения и этимологии берутся из Викисловаря и превращаются в настоящий граф.",
      "ja": "定義と語源はウィクショナリーから取得し、本格的なグラフに変換しています。",
      "zh-Hans": "释义和词源来自维基词典，并解析成一张真正的图。",
      "ko": "뜻풀이와 어원은 위키낱말사전에서 가져와 제대로 된 그래프로 변환합니다.",
      "ar": "التعريفات وأصول الكلمات مصدرها ويكاموس، محوّلة إلى رسم بياني حقيقي."
    },
    "landing.f4.title": {
      "en": "No ads, ever",
      "es": "Sin anuncios, nunca",
      "fr": "Aucune publicité, jamais",
      "de": "Niemals Werbung",
      "pt": "Sem anúncios, nunca",
      "it": "Nessuna pubblicità, mai",
      "nl": "Nooit advertenties",
      "ru": "Никакой рекламы",
      "ja": "広告は一切なし",
      "zh-Hans": "永不含广告",
      "ko": "광고는 절대 없습니다",
      "ar": "بلا إعلانات، أبداً"
    },
    "landing.f4.body": {
      "en": "The big dictionary apps are covered in ads and have no etymology. This has neither problem.",
      "es": "Las grandes apps de diccionario están llenas de anuncios y no tienen etimología. Esta no tiene ninguno de los dos problemas.",
      "fr": "Les grandes applis de dictionnaire sont couvertes de publicités et n’ont pas d’étymologie. Celle-ci n’a ni l’un ni l’autre.",
      "de": "Die großen Wörterbuch-Apps sind voller Werbung und bieten keine Etymologie. Diese hat keins von beidem.",
      "pt": "As grandes aplicações de dicionário estão cheias de anúncios e não têm etimologia. Esta não tem nenhum dos dois problemas.",
      "it": "Le grandi app di dizionario sono piene di pubblicità e non hanno etimologia. Questa non ha nessuno dei due problemi.",
      "nl": "De grote woordenboek-apps staan vol advertenties en hebben geen etymologie. Deze heeft geen van beide problemen.",
      "ru": "Крупные словарные приложения увешаны рекламой и не дают этимологии. Здесь нет ни того, ни другого.",
      "ja": "大手の辞書アプリは広告だらけで語源もない。これはそのどちらの問題もありません。",
      "zh-Hans": "大牌词典应用满是广告，又没有词源。这两个问题它都没有。",
      "ko": "유명 사전 앱은 광고투성이에 어원도 없습니다. 여기엔 두 문제 모두 없습니다.",
      "ar": "تطبيقات القواميس الكبرى مليئة بالإعلانات وتخلو من أصول الكلمات. هنا لا وجود لأيٍّ من المشكلتين."
    },
    "landing.f5.title": {
      "en": "Clean dictionary UX",
      "es": "Una experiencia de diccionario limpia",
      "fr": "Une expérience de dictionnaire épurée",
      "de": "Aufgeräumte Wörterbuch-Bedienung",
      "pt": "Uma experiência de dicionário limpa",
      "it": "Un’esperienza da dizionario pulita",
      "nl": "Heldere woordenboekervaring",
      "ru": "Чистый интерфейс словаря",
      "ja": "すっきりした辞書体験",
      "zh-Hans": "清爽的词典体验",
      "ko": "깔끔한 사전 경험",
      "ar": "تجربة قاموس أنيقة"
    },
    "landing.f5.body": {
      "en": "Fast lookup first. The deep history is one tap away, never in the way.",
      "es": "Primero la búsqueda rápida. La historia profunda está a un toque, nunca estorba.",
      "fr": "La recherche rapide d’abord. L’histoire profonde est à un geste, jamais dans le chemin.",
      "de": "Zuerst das schnelle Nachschlagen. Die tiefe Geschichte ist einen Tipp entfernt, nie im Weg.",
      "pt": "Primeiro a pesquisa rápida. A história profunda fica a um toque, nunca no caminho.",
      "it": "Prima la ricerca veloce. La storia profonda è a un tocco, mai d’intralcio.",
      "nl": "Eerst snel opzoeken. De diepe geschiedenis is één tik ver, nooit in de weg.",
      "ru": "Сначала быстрый поиск. Глубокая история — в одно касание и никогда не мешает.",
      "ja": "まずは素早く引ける。深い歴史はワンタップ先にあり、邪魔になりません。",
      "zh-Hans": "先求查得快。深层历史只需轻点一下，绝不碍事。",
      "ko": "먼저 빠른 검색. 깊은 역사는 한 번의 탭 거리에 있고, 결코 방해되지 않습니다.",
      "ar": "البحث السريع أولاً. التاريخ العميق على بُعد نقرة واحدة، ولا يعترض طريقك أبداً."
    },
    "landing.f6.title": {
      "en": "iOS, Mac, and web",
      "es": "iOS, Mac y web",
      "fr": "iOS, Mac et web",
      "de": "iOS, Mac und Web",
      "pt": "iOS, Mac e web",
      "it": "iOS, Mac e web",
      "nl": "iOS, Mac en web",
      "ru": "iOS, Mac и веб",
      "ja": "iOS・Mac・ウェブ",
      "zh-Hans": "iOS、Mac 和网页",
      "ko": "iOS, Mac, 웹",
      "ar": "iOS وMac والويب"
    },
    "landing.f6.body": {
      "en": "One dataset, three places to read it. Nothing to sign up for.",
      "es": "Un mismo conjunto de datos, tres sitios donde leerlo. Sin registros.",
      "fr": "Un seul jeu de données, trois endroits pour le lire. Aucune inscription.",
      "de": "Ein Datensatz, drei Orte zum Lesen. Keine Anmeldung nötig.",
      "pt": "Um conjunto de dados, três sítios para o ler. Sem registos.",
      "it": "Un solo set di dati, tre posti dove leggerlo. Nessuna registrazione.",
      "nl": "Eén dataset, drie plekken om die te lezen. Niets om je voor aan te melden.",
      "ru": "Один набор данных, три места, где его читать. Регистрация не нужна.",
      "ja": "ひとつのデータセットを、3 つの場所で。登録は不要です。",
      "zh-Hans": "同一份数据，三处可读。无需注册。",
      "ko": "하나의 데이터셋, 읽을 수 있는 세 곳. 가입할 것은 없습니다.",
      "ar": "مجموعة بيانات واحدة، وثلاثة أماكن لقراءتها. لا حاجة للتسجيل."
    },
    "landing.closing.title": {
      "en": "Start with a word",
      "es": "Empieza con una palabra",
      "fr": "Commencez par un mot",
      "de": "Fang mit einem Wort an",
      "pt": "Comece com uma palavra",
      "it": "Inizia da una parola",
      "nl": "Begin met een woord",
      "ru": "Начните со слова",
      "ja": "まずは一語から",
      "zh-Hans": "从一个词开始",
      "ko": "단어 하나로 시작하세요",
      "ar": "ابدأ بكلمة"
    },
    "landing.closing.body": {
      "en": "No account, no install required. Open the web app and look something up.",
      "es": "Sin cuenta ni instalación. Abre la app web y busca algo.",
      "fr": "Sans compte ni installation. Ouvrez l’application web et cherchez un mot.",
      "de": "Kein Konto, keine Installation nötig. Öffne die Web-App und schlag etwas nach.",
      "pt": "Sem conta nem instalação. Abra a aplicação web e procure algo.",
      "it": "Nessun account, nessuna installazione. Apri l’app web e cerca qualcosa.",
      "nl": "Geen account, geen installatie nodig. Open de web-app en zoek iets op.",
      "ru": "Ни аккаунта, ни установки. Откройте веб-приложение и найдите слово.",
      "ja": "アカウントもインストールも不要。ウェブアプリを開いて調べてみてください。",
      "zh-Hans": "无需账号，无需安装。打开网页应用查一个词。",
      "ko": "계정도 설치도 필요 없습니다. 웹 앱을 열고 찾아보세요.",
      "ar": "بلا حساب ولا تثبيت. افتح تطبيق الويب وابحث عن كلمة."
    },
    "landing.footer.by": {
      "en": "Wordroot — by",
      "es": "Wordroot — por",
      "fr": "Wordroot — par",
      "de": "Wordroot — von",
      "pt": "Wordroot — por",
      "it": "Wordroot — di",
      "nl": "Wordroot — door",
      "ru": "Wordroot — автор:",
      "ja": "Wordroot — 制作:",
      "zh-Hans": "Wordroot — 作者",
      "ko": "Wordroot — 제작:",
      "ar": "Wordroot — بواسطة"
    },
    "landing.footer.source": {
      "en": "Source on GitHub",
      "es": "Código en GitHub",
      "fr": "Code source sur GitHub",
      "de": "Quellcode auf GitHub",
      "pt": "Código no GitHub",
      "it": "Codice su GitHub",
      "nl": "Broncode op GitHub",
      "ru": "Исходный код на GitHub",
      "ja": "GitHub のソース",
      "zh-Hans": "GitHub 源码",
      "ko": "GitHub 소스",
      "ar": "الشيفرة على GitHub"
    },
    "landing.footer.api": {
      "en": "API",
      "es": "API",
      "fr": "API",
      "de": "API",
      "pt": "API",
      "it": "API",
      "nl": "API",
      "ru": "API",
      "ja": "API",
      "zh-Hans": "API",
      "ko": "API",
      "ar": "API"
    }
  },
  "wall": [
    {
      "word": "candid",
      "form": "candidus",
      "meaning": {
        "en": "white",
        "es": "blanco",
        "fr": "blanc",
        "de": "weiß",
        "pt": "branco",
        "it": "bianco",
        "nl": "wit",
        "ru": "белый",
        "ja": "白い",
        "zh-Hans": "白色",
        "ko": "하얀",
        "ar": "أبيض"
      }
    },
    {
      "word": "sincere",
      "form": "sine cera",
      "meaning": {
        "en": "without wax",
        "es": "sin cera",
        "fr": "sans cire",
        "de": "ohne Wachs",
        "pt": "sem cera",
        "it": "senza cera",
        "nl": "zonder was",
        "ru": "без воска",
        "ja": "蝋なし",
        "zh-Hans": "没有蜡",
        "ko": "밀랍 없이",
        "ar": "بلا شمع"
      }
    },
    {
      "word": "muscle",
      "form": "musculus",
      "meaning": {
        "en": "little mouse",
        "es": "ratoncillo",
        "fr": "petite souris",
        "de": "Mäuschen",
        "pt": "ratinho",
        "it": "topolino",
        "nl": "muisje",
        "ru": "мышка",
        "ja": "小さなネズミ",
        "zh-Hans": "小老鼠",
        "ko": "작은 쥐",
        "ar": "فأر صغير"
      }
    },
    {
      "word": "salary",
      "form": "salarium",
      "meaning": {
        "en": "salt money",
        "es": "dinero de sal",
        "fr": "argent du sel",
        "de": "Salzgeld",
        "pt": "dinheiro do sal",
        "it": "denaro del sale",
        "nl": "zoutgeld",
        "ru": "соляные деньги",
        "ja": "塩の代金",
        "zh-Hans": "盐钱",
        "ko": "소금 값",
        "ar": "مال الملح"
      }
    },
    {
      "word": "disaster",
      "form": "dis-astro",
      "meaning": {
        "en": "ill-starred",
        "es": "de mal astro",
        "fr": "sous une mauvaise étoile",
        "de": "unter schlechtem Stern",
        "pt": "de mau astro",
        "it": "sotto cattiva stella",
        "nl": "onder een kwaad gesternte",
        "ru": "под несчастливой звездой",
        "ja": "不吉な星",
        "zh-Hans": "恶星当头",
        "ko": "불길한 별",
        "ar": "نجم نحس"
      }
    },
    {
      "word": "companion",
      "form": "com panis",
      "meaning": {
        "en": "with bread",
        "es": "con pan",
        "fr": "avec du pain",
        "de": "mit Brot",
        "pt": "com pão",
        "it": "con il pane",
        "nl": "met brood",
        "ru": "с хлебом",
        "ja": "パンを共に",
        "zh-Hans": "共享面包",
        "ko": "빵을 함께",
        "ar": "مع الخبز"
      }
    },
    {
      "word": "clue",
      "form": "clew",
      "meaning": {
        "en": "ball of thread",
        "es": "ovillo de hilo",
        "fr": "pelote de fil",
        "de": "Garnknäuel",
        "pt": "novelo de fio",
        "it": "gomitolo di filo",
        "nl": "kluwen garen",
        "ru": "клубок нити",
        "ja": "糸玉",
        "zh-Hans": "线团",
        "ko": "실뭉치",
        "ar": "كبة خيط"
      }
    },
    {
      "word": "sarcasm",
      "form": "sarkazein",
      "meaning": {
        "en": "to tear flesh",
        "es": "desgarrar la carne",
        "fr": "déchirer la chair",
        "de": "Fleisch zerreißen",
        "pt": "rasgar a carne",
        "it": "lacerare la carne",
        "nl": "vlees scheuren",
        "ru": "рвать плоть",
        "ja": "肉を裂く",
        "zh-Hans": "撕裂血肉",
        "ko": "살을 찢다",
        "ar": "تمزيق اللحم"
      }
    },
    {
      "word": "nostalgia",
      "form": "nostos algos",
      "meaning": {
        "en": "homecoming pain",
        "es": "dolor del regreso",
        "fr": "douleur du retour",
        "de": "Heimkehrschmerz",
        "pt": "dor do regresso",
        "it": "dolore del ritorno",
        "nl": "thuiskomstpijn",
        "ru": "боль возвращения",
        "ja": "帰郷の痛み",
        "zh-Hans": "归乡之痛",
        "ko": "귀향의 고통",
        "ar": "ألم العودة"
      }
    },
    {
      "word": "quarantine",
      "form": "quaranta",
      "meaning": {
        "en": "forty days",
        "es": "cuarenta días",
        "fr": "quarante jours",
        "de": "vierzig Tage",
        "pt": "quarenta dias",
        "it": "quaranta giorni",
        "nl": "veertig dagen",
        "ru": "сорок дней",
        "ja": "四十日",
        "zh-Hans": "四十天",
        "ko": "사십 일",
        "ar": "أربعون يوماً"
      }
    },
    {
      "word": "galaxy",
      "form": "gala",
      "meaning": {
        "en": "milk",
        "es": "leche",
        "fr": "lait",
        "de": "Milch",
        "pt": "leite",
        "it": "latte",
        "nl": "melk",
        "ru": "молоко",
        "ja": "乳",
        "zh-Hans": "乳汁",
        "ko": "젖",
        "ar": "حليب"
      }
    },
    {
      "word": "orient",
      "form": "oriens",
      "meaning": {
        "en": "rising sun",
        "es": "sol naciente",
        "fr": "soleil levant",
        "de": "aufgehende Sonne",
        "pt": "sol nascente",
        "it": "sole nascente",
        "nl": "opkomende zon",
        "ru": "восходящее солнце",
        "ja": "昇る太陽",
        "zh-Hans": "旭日",
        "ko": "떠오르는 해",
        "ar": "شمس شارقة"
      }
    },
    {
      "word": "tragedy",
      "form": "tragoidia",
      "meaning": {
        "en": "goat song",
        "es": "canto del macho cabrío",
        "fr": "chant du bouc",
        "de": "Bocksgesang",
        "pt": "canto do bode",
        "it": "canto del capro",
        "nl": "bokkenzang",
        "ru": "козлиная песнь",
        "ja": "山羊の歌",
        "zh-Hans": "山羊之歌",
        "ko": "염소의 노래",
        "ar": "أغنية التيس"
      }
    },
    {
      "word": "calculate",
      "form": "calculus",
      "meaning": {
        "en": "pebble",
        "es": "guijarro",
        "fr": "caillou",
        "de": "Kieselstein",
        "pt": "seixo",
        "it": "sassolino",
        "nl": "kiezelsteen",
        "ru": "камешек",
        "ja": "小石",
        "zh-Hans": "小石子",
        "ko": "조약돌",
        "ar": "حصاة"
      }
    },
    {
      "word": "lunatic",
      "form": "luna",
      "meaning": {
        "en": "moon",
        "es": "luna",
        "fr": "lune",
        "de": "Mond",
        "pt": "lua",
        "it": "luna",
        "nl": "maan",
        "ru": "луна",
        "ja": "月",
        "zh-Hans": "月亮",
        "ko": "달",
        "ar": "قمر"
      }
    },
    {
      "word": "pupil",
      "form": "pupilla",
      "meaning": {
        "en": "little doll",
        "es": "muñequita",
        "fr": "petite poupée",
        "de": "Püppchen",
        "pt": "bonequinha",
        "it": "bambolina",
        "nl": "popje",
        "ru": "куколка",
        "ja": "小さな人形",
        "zh-Hans": "小娃娃",
        "ko": "작은 인형",
        "ar": "دمية صغيرة"
      }
    },
    {
      "word": "rival",
      "form": "rivalis",
      "meaning": {
        "en": "same stream",
        "es": "del mismo río",
        "fr": "du même cours d’eau",
        "de": "am selben Bach",
        "pt": "do mesmo rio",
        "it": "dello stesso ruscello",
        "nl": "van dezelfde beek",
        "ru": "с одного ручья",
        "ja": "同じ川の",
        "zh-Hans": "同一条溪",
        "ko": "같은 개울",
        "ar": "من النهر ذاته"
      }
    },
    {
      "word": "precocious",
      "form": "praecox",
      "meaning": {
        "en": "ripening early",
        "es": "que madura pronto",
        "fr": "mûrissant tôt",
        "de": "früh reifend",
        "pt": "que amadurece cedo",
        "it": "che matura presto",
        "nl": "vroeg rijpend",
        "ru": "рано созревающий",
        "ja": "早熟",
        "zh-Hans": "早熟",
        "ko": "일찍 익는",
        "ar": "مبكر النضج"
      }
    },
    {
      "word": "sabotage",
      "form": "sabot",
      "meaning": {
        "en": "wooden shoe",
        "es": "zueco de madera",
        "fr": "sabot de bois",
        "de": "Holzschuh",
        "pt": "tamanco de madeira",
        "it": "zoccolo di legno",
        "nl": "houten klomp",
        "ru": "деревянный башмак",
        "ja": "木靴",
        "zh-Hans": "木鞋",
        "ko": "나막신",
        "ar": "حذاء خشبي"
      }
    },
    {
      "word": "vaccine",
      "form": "vacca",
      "meaning": {
        "en": "cow",
        "es": "vaca",
        "fr": "vache",
        "de": "Kuh",
        "pt": "vaca",
        "it": "vacca",
        "nl": "koe",
        "ru": "корова",
        "ja": "雌牛",
        "zh-Hans": "母牛",
        "ko": "암소",
        "ar": "بقرة"
      }
    },
    {
      "word": "alcohol",
      "form": "al-kuhl",
      "meaning": {
        "en": "the kohl",
        "es": "el kohl",
        "fr": "le khôl",
        "de": "das Kajal",
        "pt": "o kohl",
        "it": "il kohl",
        "nl": "de kohl",
        "ru": "сурьма",
        "ja": "コホル",
        "zh-Hans": "眼影粉",
        "ko": "콜 가루",
        "ar": "الكحل"
      }
    },
    {
      "word": "algebra",
      "form": "al-jabr",
      "meaning": {
        "en": "reunion of parts",
        "es": "reunión de partes",
        "fr": "réunion des parties",
        "de": "Zusammenfügen der Teile",
        "pt": "reunião das partes",
        "it": "ricongiungimento delle parti",
        "nl": "samenvoegen van delen",
        "ru": "соединение частей",
        "ja": "部分の再結合",
        "zh-Hans": "断片重聚",
        "ko": "부분의 재결합",
        "ar": "جبر الأجزاء"
      }
    },
    {
      "word": "assassin",
      "form": "hashishin",
      "meaning": {
        "en": "hashish user",
        "es": "consumidor de hachís",
        "fr": "consommateur de haschich",
        "de": "Haschischesser",
        "pt": "consumidor de haxixe",
        "it": "consumatore di hashish",
        "nl": "hasjgebruiker",
        "ru": "употребляющий гашиш",
        "ja": "ハシシ使用者",
        "zh-Hans": "食大麻者",
        "ko": "하시시 복용자",
        "ar": "متعاطي الحشيش"
      }
    },
    {
      "word": "candidate",
      "form": "candidatus",
      "meaning": {
        "en": "robed in white",
        "es": "vestido de blanco",
        "fr": "vêtu de blanc",
        "de": "weiß gewandet",
        "pt": "vestido de branco",
        "it": "vestito di bianco",
        "nl": "in het wit gekleed",
        "ru": "облачённый в белое",
        "ja": "白衣の",
        "zh-Hans": "身着白袍",
        "ko": "흰옷을 입은",
        "ar": "مرتدٍ البياض"
      }
    },
    {
      "word": "dexterity",
      "form": "dexter",
      "meaning": {
        "en": "right-handed",
        "es": "diestro",
        "fr": "droitier",
        "de": "rechtshändig",
        "pt": "destro",
        "it": "destro",
        "nl": "rechtshandig",
        "ru": "правша",
        "ja": "右利き",
        "zh-Hans": "右手的",
        "ko": "오른손잡이",
        "ar": "أيمن"
      }
    },
    {
      "word": "sinister",
      "form": "sinister",
      "meaning": {
        "en": "left-handed",
        "es": "zurdo",
        "fr": "gaucher",
        "de": "linkshändig",
        "pt": "canhoto",
        "it": "mancino",
        "nl": "linkshandig",
        "ru": "левша",
        "ja": "左利き",
        "zh-Hans": "左手的",
        "ko": "왼손잡이",
        "ar": "أعسر"
      }
    },
    {
      "word": "husband",
      "form": "hus bondi",
      "meaning": {
        "en": "house dweller",
        "es": "morador de la casa",
        "fr": "habitant de la maison",
        "de": "Hausbewohner",
        "pt": "morador da casa",
        "it": "abitante della casa",
        "nl": "huisbewoner",
        "ru": "обитатель дома",
        "ja": "家に住む者",
        "zh-Hans": "住屋之人",
        "ko": "집에 사는 이",
        "ar": "ساكن البيت"
      }
    },
    {
      "word": "window",
      "form": "vindauga",
      "meaning": {
        "en": "wind eye",
        "es": "ojo del viento",
        "fr": "œil du vent",
        "de": "Windauge",
        "pt": "olho do vento",
        "it": "occhio del vento",
        "nl": "windoog",
        "ru": "глаз ветра",
        "ja": "風の目",
        "zh-Hans": "风之眼",
        "ko": "바람의 눈",
        "ar": "عين الريح"
      }
    },
    {
      "word": "daisy",
      "form": "daeges eage",
      "meaning": {
        "en": "day’s eye",
        "es": "ojo del día",
        "fr": "œil du jour",
        "de": "Tagesauge",
        "pt": "olho do dia",
        "it": "occhio del giorno",
        "nl": "dagoog",
        "ru": "глаз дня",
        "ja": "昼の目",
        "zh-Hans": "白日之眼",
        "ko": "낮의 눈",
        "ar": "عين النهار"
      }
    },
    {
      "word": "gossip",
      "form": "godsibb",
      "meaning": {
        "en": "godparent",
        "es": "padrino",
        "fr": "parrain",
        "de": "Pate",
        "pt": "padrinho",
        "it": "padrino",
        "nl": "peetouder",
        "ru": "крёстный",
        "ja": "名づけ親",
        "zh-Hans": "教父母",
        "ko": "대부모",
        "ar": "عرّاب"
      }
    },
    {
      "word": "nice",
      "form": "nescius",
      "meaning": {
        "en": "ignorant",
        "es": "ignorante",
        "fr": "ignorant",
        "de": "unwissend",
        "pt": "ignorante",
        "it": "ignorante",
        "nl": "onwetend",
        "ru": "невежественный",
        "ja": "無知な",
        "zh-Hans": "无知的",
        "ko": "무지한",
        "ar": "جاهل"
      }
    },
    {
      "word": "silly",
      "form": "saelig",
      "meaning": {
        "en": "blessed",
        "es": "bienaventurado",
        "fr": "bienheureux",
        "de": "selig",
        "pt": "bem-aventurado",
        "it": "beato",
        "nl": "zalig",
        "ru": "блаженный",
        "ja": "祝福された",
        "zh-Hans": "蒙福的",
        "ko": "축복받은",
        "ar": "مبارَك"
      }
    },
    {
      "word": "panic",
      "form": "Pan",
      "meaning": {
        "en": "the god",
        "es": "el dios",
        "fr": "le dieu",
        "de": "der Gott",
        "pt": "o deus",
        "it": "il dio",
        "nl": "de god",
        "ru": "бог",
        "ja": "神",
        "zh-Hans": "神祇",
        "ko": "그 신",
        "ar": "الإله"
      }
    },
    {
      "word": "cereal",
      "form": "Ceres",
      "meaning": {
        "en": "goddess of grain",
        "es": "diosa del grano",
        "fr": "déesse des moissons",
        "de": "Göttin des Getreides",
        "pt": "deusa dos cereais",
        "it": "dea del grano",
        "nl": "godin van het graan",
        "ru": "богиня зерна",
        "ja": "穀物の女神",
        "zh-Hans": "谷物女神",
        "ko": "곡물의 여신",
        "ar": "إلهة الحبوب"
      }
    },
    {
      "word": "january",
      "form": "Janus",
      "meaning": {
        "en": "two-faced god",
        "es": "dios de dos caras",
        "fr": "dieu à deux visages",
        "de": "zweigesichtiger Gott",
        "pt": "deus de duas faces",
        "it": "dio bifronte",
        "nl": "tweegezichtige god",
        "ru": "двуликий бог",
        "ja": "双面の神",
        "zh-Hans": "双面之神",
        "ko": "두 얼굴의 신",
        "ar": "إله بوجهين"
      }
    },
    {
      "word": "volcano",
      "form": "Vulcan",
      "meaning": {
        "en": "god of fire",
        "es": "dios del fuego",
        "fr": "dieu du feu",
        "de": "Gott des Feuers",
        "pt": "deus do fogo",
        "it": "dio del fuoco",
        "nl": "god van het vuur",
        "ru": "бог огня",
        "ja": "火の神",
        "zh-Hans": "火神",
        "ko": "불의 신",
        "ar": "إله النار"
      }
    },
    {
      "word": "atlas",
      "form": "Atlas",
      "meaning": {
        "en": "the titan",
        "es": "el titán",
        "fr": "le titan",
        "de": "der Titan",
        "pt": "o titã",
        "it": "il titano",
        "nl": "de titaan",
        "ru": "титан",
        "ja": "ティタン",
        "zh-Hans": "泰坦",
        "ko": "티탄",
        "ar": "التيتان"
      }
    },
    {
      "word": "echo",
      "form": "Echo",
      "meaning": {
        "en": "the nymph",
        "es": "la ninfa",
        "fr": "la nymphe",
        "de": "die Nymphe",
        "pt": "a ninfa",
        "it": "la ninfa",
        "nl": "de nimf",
        "ru": "нимфа",
        "ja": "ニンフ",
        "zh-Hans": "仙女",
        "ko": "님프",
        "ar": "الحورية"
      }
    },
    {
      "word": "robot",
      "form": "robota",
      "meaning": {
        "en": "forced labour",
        "es": "trabajo forzado",
        "fr": "travail forcé",
        "de": "Zwangsarbeit",
        "pt": "trabalho forçado",
        "it": "lavoro forzato",
        "nl": "dwangarbeid",
        "ru": "подневольный труд",
        "ja": "強制労働",
        "zh-Hans": "强迫劳役",
        "ko": "강제 노동",
        "ar": "عمل قسري"
      }
    },
    {
      "word": "nightmare",
      "form": "mare",
      "meaning": {
        "en": "crushing spirit",
        "es": "espíritu que oprime",
        "fr": "esprit oppresseur",
        "de": "erdrückender Geist",
        "pt": "espírito opressor",
        "it": "spirito opprimente",
        "nl": "beklemmende geest",
        "ru": "давящий дух",
        "ja": "押しつぶす霊",
        "zh-Hans": "压身之魔",
        "ko": "짓누르는 정령",
        "ar": "روح جاثمة"
      }
    }
  ]
};

  var STORAGE_KEY = 'wordroot.uiLang';
  var codes = DATA.locales.map(function (l) { return l.code; });

  // Chinese is offered in Simplified only, so every zh variant — zh, zh-CN, zh-Hant-TW —
  // negotiates to it rather than falling through to English.
  function normalize(tag) {
    if (!tag) return null;
    tag = String(tag).replace(/_/g, '-');
    if (/^zh\b/i.test(tag)) return codes.indexOf('zh-Hans') >= 0 ? 'zh-Hans' : null;
    var parts = tag.split('-');
    while (parts.length) {
      var candidate = parts.join('-');
      for (var i = 0; i < codes.length; i++) {
        if (codes[i].toLowerCase() === candidate.toLowerCase()) return codes[i];
      }
      parts.pop();
    }
    return null;
  }

  function stored(key) {
    try { return localStorage.getItem(key); } catch (e) { return null; }  // Safari private mode throws
  }

  function negotiate() {
    var params = new URLSearchParams(location.search);
    var wanted = [params.get('lang'), stored(STORAGE_KEY)]
      .concat(navigator.languages || [navigator.language]);
    for (var i = 0; i < wanted.length; i++) {
      var hit = normalize(wanted[i]);
      if (hit) return hit;
    }
    return 'en';
  }

  var locale = negotiate();
  var meta = DATA.locales.filter(function (l) { return l.code === locale; })[0];

  var displayNames = null;
  try {
    displayNames = new Intl.DisplayNames([locale, 'en'], { type: 'language' });
  } catch (e) { /* pre-2021 browsers: fall back to the English table below */ }

  var i18n = {
    locale: locale,
    dir: (meta && meta.dir) || 'ltr',
    locales: DATA.locales,
    wordLanguages: DATA.wordLanguages || [],
    wordsOfTheDay: DATA.wordsOfTheDay || {},

    /**
     * Landing-page hero wall, meanings already resolved to this locale. The headword and its
     * source form are proper forms and stay as they are.
     */
    wall: (DATA.wall || []).map(function (e) {
      return { word: e.word, form: e.form, meaning: e.meaning[locale] || e.meaning.en };
    }),

    /** Translate `key`, substituting {name} placeholders from `vars`. */
    t: function (key, vars) {
      var row = DATA.strings[key];
      var s = (row && (row[locale] || row.en)) || key;
      if (!vars) return s;
      return s.replace(/\{(\w+)\}/g, function (m, name) {
        return Object.prototype.hasOwnProperty.call(vars, name) ? vars[name] : m;
      });
    },

    /**
     * Localized name for a language code from a Wiktionary etymology template.
     * Hand translations win, then CLDR, then the English table, then the raw code —
     * so an unrecognized code still renders as itself rather than as an empty cell.
     */
    languageName: function (code) {
      if (!code) return '';
      if (DATA.strings['lang.' + code]) return i18n.t('lang.' + code);
      if (displayNames) {
        try {
          var name = displayNames.of(code);
          if (name && name !== code) return name;
        } catch (e) { /* not a well-formed BCP 47 tag, e.g. "NL." */ }
      }
      return (DATA.ancestorLanguages || {})[code] || code;
    },

    /** Persist a new interface language and reload so every string re-renders. */
    setLocale: function (code) {
      if (!normalize(code)) return;
      try { localStorage.setItem(STORAGE_KEY, code); } catch (e) { /* storage disabled */ }
      var url = new URL(location.href);
      url.searchParams.delete('lang');  // the stored choice is now authoritative
      location.replace(url.toString());
    },

    /** Point <html lang>/<html dir> at the negotiated locale. Safe to call before <body>. */
    applyDocumentLanguage: function () {
      document.documentElement.lang = locale;
      document.documentElement.dir = i18n.dir;
    },

    /** <select> of interface languages, wired to setLocale. */
    localePicker: function (label) {
      var sel = document.createElement('select');
      sel.setAttribute('aria-label', label);
      DATA.locales.forEach(function (l) {
        var opt = document.createElement('option');
        opt.value = l.code;
        opt.textContent = l.endonym;
        opt.lang = l.code;
        if (l.code === locale) opt.selected = true;
        sel.appendChild(opt);
      });
      sel.addEventListener('change', function () { i18n.setLocale(sel.value); });
      return sel;
    },
  };

  window.i18n = i18n;
})();
