#!/usr/bin/env python3
"""Generate the per-surface i18n bundles from i18n/strings.json.

One catalog, three outputs — web/i18n.js, landing/i18n.js and ios/Sources/Localized.swift —
so a string can never drift between the web app, the landing page and the Apple apps. Each
output carries only the keys its surface actually renders.

    python3 scripts/gen-i18n.py            # write the generated files
    python3 scripts/gen-i18n.py --check    # fail if they are stale (used by build-site.sh)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "i18n" / "strings.json"

# Which key prefixes each surface renders. `app.` and `ui.` are shared; the landing page has
# no lookup UI and the apps have no marketing copy, so neither ships the other's strings.
SURFACES = {
    "web": ("app.", "web.", "ui.", "rel.", "lang.", "privacy."),
    "landing": ("app.", "ui.language", "ui.privacy", "landing."),
    "ios": ("app.", "ui.", "rel.", "lang."),
}

BANNER = "GENERATED by scripts/gen-i18n.py from i18n/strings.json — do not edit by hand."


def subset(strings, prefixes):
    return {k: v for k, v in strings.items() if any(k.startswith(p) for p in prefixes)}


def js_bundle(cat, keys, lookup_data, wall=False):
    """Data + runtime. Emitted verbatim into both web/ and landing/ so each stays standalone.

    `lookup_data` carries the dictionary tables; the landing page has no lookup UI, so it
    ships the runtime and its own copy without them.
    """
    data = {"locales": cat["locales"], "strings": keys}
    if wall:
        data["wall"] = cat["wall"]
    if lookup_data:
        data["wordLanguages"] = cat["wordLanguages"]
        data["ancestorLanguages"] = cat["ancestorLanguages"]
        data["wordsOfTheDay"] = cat["wordsOfTheDay"]
    return f"""// {BANNER}
//
// Exposes `window.i18n`: the string table plus the small runtime the pages share —
// locale negotiation, persistence, {{placeholder}} interpolation and localized language
// names. No framework, no build step at page load; the file is the bundle.
(function () {{
  var DATA = {json.dumps(data, ensure_ascii=False, indent=2, sort_keys=False)};

  var STORAGE_KEY = 'wordroot.uiLang';
  var codes = DATA.locales.map(function (l) {{ return l.code; }});

  // Chinese is offered in Simplified only, so every zh variant — zh, zh-CN, zh-Hant-TW —
  // negotiates to it rather than falling through to English.
  function normalize(tag) {{
    if (!tag) return null;
    tag = String(tag).replace(/_/g, '-');
    if (/^zh\\b/i.test(tag)) return codes.indexOf('zh-Hans') >= 0 ? 'zh-Hans' : null;
    var parts = tag.split('-');
    while (parts.length) {{
      var candidate = parts.join('-');
      for (var i = 0; i < codes.length; i++) {{
        if (codes[i].toLowerCase() === candidate.toLowerCase()) return codes[i];
      }}
      parts.pop();
    }}
    return null;
  }}

  function stored(key) {{
    try {{ return localStorage.getItem(key); }} catch (e) {{ return null; }}  // Safari private mode throws
  }}

  function negotiate() {{
    var params = new URLSearchParams(location.search);
    var wanted = [params.get('lang'), stored(STORAGE_KEY)]
      .concat(navigator.languages || [navigator.language]);
    for (var i = 0; i < wanted.length; i++) {{
      var hit = normalize(wanted[i]);
      if (hit) return hit;
    }}
    return 'en';
  }}

  var locale = negotiate();
  var meta = DATA.locales.filter(function (l) {{ return l.code === locale; }})[0];

  var displayNames = null;
  try {{
    displayNames = new Intl.DisplayNames([locale, 'en'], {{ type: 'language' }});
  }} catch (e) {{ /* pre-2021 browsers: fall back to the English table below */ }}

  var i18n = {{
    locale: locale,
    dir: (meta && meta.dir) || 'ltr',
    locales: DATA.locales,
    wordLanguages: DATA.wordLanguages || [],
    wordsOfTheDay: DATA.wordsOfTheDay || {{}},

    /**
     * Landing-page hero wall, meanings already resolved to this locale. The headword and its
     * source form are proper forms and stay as they are.
     */
    wall: (DATA.wall || []).map(function (e) {{
      return {{ word: e.word, form: e.form, meaning: e.meaning[locale] || e.meaning.en }};
    }}),

    /** Translate `key`, substituting {{name}} placeholders from `vars`. */
    t: function (key, vars) {{
      var row = DATA.strings[key];
      var s = (row && (row[locale] || row.en)) || key;
      if (!vars) return s;
      return s.replace(/\\{{(\\w+)\\}}/g, function (m, name) {{
        return Object.prototype.hasOwnProperty.call(vars, name) ? vars[name] : m;
      }});
    }},

    /**
     * Localized name for a language code from a Wiktionary etymology template.
     * Hand translations win, then CLDR, then the English table, then the raw code —
     * so an unrecognized code still renders as itself rather than as an empty cell.
     */
    languageName: function (code) {{
      if (!code) return '';
      if (DATA.strings['lang.' + code]) return i18n.t('lang.' + code);
      if (displayNames) {{
        try {{
          var name = displayNames.of(code);
          if (name && name !== code) return name;
        }} catch (e) {{ /* not a well-formed BCP 47 tag, e.g. "NL." */ }}
      }}
      return (DATA.ancestorLanguages || {{}})[code] || code;
    }},

    /** Persist a new interface language and reload so every string re-renders. */
    setLocale: function (code) {{
      if (!normalize(code)) return;
      try {{ localStorage.setItem(STORAGE_KEY, code); }} catch (e) {{ /* storage disabled */ }}
      var url = new URL(location.href);
      url.searchParams.delete('lang');  // the stored choice is now authoritative
      location.replace(url.toString());
    }},

    /** Point <html lang>/<html dir> at the negotiated locale. Safe to call before <body>. */
    applyDocumentLanguage: function () {{
      document.documentElement.lang = locale;
      document.documentElement.dir = i18n.dir;
    }},

    /** <select> of interface languages, wired to setLocale. */
    localePicker: function (label) {{
      var sel = document.createElement('select');
      sel.setAttribute('aria-label', label);
      DATA.locales.forEach(function (l) {{
        var opt = document.createElement('option');
        opt.value = l.code;
        opt.textContent = l.endonym;
        opt.lang = l.code;
        if (l.code === locale) opt.selected = true;
        sel.appendChild(opt);
      }});
      sel.addEventListener('change', function () {{ i18n.setLocale(sel.value); }});
      return sel;
    }},
  }};

  window.i18n = i18n;
}})();
"""


def swift_bundle(cat, keys):
    locales = [l["code"] for l in cat["locales"]]

    def lit(s):
        return json.dumps(s, ensure_ascii=False)

    tables = []
    for code in locales:
        rows = "".join(f"        {lit(k)}: {lit(v[code])},\n" for k, v in keys.items())
        # One table per locale rather than one nested literal: Swift type-checks small
        # dictionaries far faster than a single 400-entry nested one.
        tables.append(
            f"    private static let {swift_ident(code)}: [String: String] = [\n{rows}    ]\n"
        )

    table_map = "".join(f"        {lit(c)}: {swift_ident(c)},\n" for c in locales)
    locale_rows = "".join(
        f"        UILanguage(code: {lit(l['code'])}, endonym: {lit(l['endonym'])}, "
        f"isRightToLeft: {'true' if l['dir'] == 'rtl' else 'false'}),\n"
        for l in cat["locales"]
    )
    word_rows = "".join(
        f"        WordLanguage(code: {lit(w['code'])}, section: {lit(w['section'])}, "
        f"englishName: {lit(w['english'])}),\n"
        for w in cat["wordLanguages"]
    )
    ancestor_rows = "".join(
        f"        {lit(k)}: {lit(v)},\n" for k, v in cat["ancestorLanguages"].items()
    )
    wotd_rows = "".join(
        f"        {lit(k)}: [{', '.join(lit(w) for w in v)}],\n"
        for k, v in cat["wordsOfTheDay"].items()
    )

    return f"""// {BANNER}
import Foundation

/// An interface language Wordroot ships strings for.
struct UILanguage: Identifiable, Hashable {{
    let code: String
    let endonym: String
    let isRightToLeft: Bool
    var id: String {{ code }}
}}

/// A language a looked-up word may be written in. `section` is the ==Heading== that language
/// uses on the English Wiktionary; `code` is the key its definitions come back under.
struct WordLanguage: Identifiable, Hashable {{
    let code: String
    let section: String
    let englishName: String
    var id: String {{ code }}
}}

enum Catalog {{
    static let uiLanguages: [UILanguage] = [
{locale_rows}    ]

    static let wordLanguages: [WordLanguage] = [
{word_rows}    ]

    /// English fallbacks for etymology-template language codes CLDR may not carry.
    static let ancestorLanguages: [String: String] = [
{ancestor_rows}    ]

    /// Word-of-the-day rotation per word language. A language absent here shows none.
    static let wordsOfTheDay: [String: [String]] = [
{wotd_rows}    ]

{"".join(tables)}
    static let tables: [String: [String: String]] = [
{table_map}    ]
}}
"""


def swift_ident(code):
    return "table_" + code.replace("-", "_")


def check_landing_hreflang(cat):
    """The landing page's <link rel=alternate> set is hand-written so crawlers see it without
    running JS; this keeps it honest against the catalog."""
    html = (ROOT / "landing" / "index.html").read_text(encoding="utf-8")
    block = re.search(r"<!-- hreflang:begin.*?-->(.*?)<!-- hreflang:end -->", html, re.S)
    if not block:
        return ["landing/index.html: hreflang block missing"]
    found = set(re.findall(r'hreflang="([^"]+)"', block.group(1)))
    want = {l["code"] for l in cat["locales"]} | {"x-default"}
    problems = []
    if found - want:
        problems.append(f"landing/index.html: hreflang for unshipped locales {sorted(found - want)}")
    if want - found:
        problems.append(f"landing/index.html: hreflang missing for {sorted(want - found)}")
    return problems


def main():
    check = "--check" in sys.argv[1:]
    cat = json.load(open(CATALOG, encoding="utf-8"))
    strings = cat["strings"]

    outputs = {
        ROOT / "web" / "i18n.js": js_bundle(cat, subset(strings, SURFACES["web"]), True),
        ROOT / "landing" / "i18n.js": js_bundle(
            cat, subset(strings, SURFACES["landing"]), False, wall=True
        ),
        ROOT / "ios" / "Sources" / "Localized.swift": swift_bundle(
            cat, subset(strings, SURFACES["ios"])
        ),
    }

    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(path.relative_to(ROOT))
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    problems = [f"stale (run scripts/gen-i18n.py): {p}" for p in stale]
    problems += check_landing_hreflang(cat)
    if problems:
        for p in problems:
            print(p, file=sys.stderr)
        return 1
    if check:
        print("i18n bundles are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
