// GENERATED by scripts/gen-i18n.py from i18n/strings.json — do not edit by hand.
//
// Exposes `window.i18n`: the string table plus the small runtime the pages share —
// locale negotiation, persistence, {placeholder} interpolation and localized language
// names. No framework, no build step at page load; the file is the bundle.
(function () {
  var DATA = {
  "locales": [
    {
      "code": "en",
      "endonym": "English",
      "dir": "ltr"
    },
    {
      "code": "es",
      "endonym": "Español",
      "dir": "ltr"
    },
    {
      "code": "fr",
      "endonym": "Français",
      "dir": "ltr"
    },
    {
      "code": "de",
      "endonym": "Deutsch",
      "dir": "ltr"
    },
    {
      "code": "pt",
      "endonym": "Português",
      "dir": "ltr"
    },
    {
      "code": "it",
      "endonym": "Italiano",
      "dir": "ltr"
    },
    {
      "code": "nl",
      "endonym": "Nederlands",
      "dir": "ltr"
    },
    {
      "code": "ru",
      "endonym": "Русский",
      "dir": "ltr"
    },
    {
      "code": "ja",
      "endonym": "日本語",
      "dir": "ltr"
    },
    {
      "code": "zh-Hans",
      "endonym": "简体中文",
      "dir": "ltr"
    },
    {
      "code": "ko",
      "endonym": "한국어",
      "dir": "ltr"
    },
    {
      "code": "ar",
      "endonym": "العربية",
      "dir": "rtl"
    }
  ],
  "strings": {
    "app.tagline": {
      "en": "Dictionary with deep etymology",
      "es": "Diccionario con etimología profunda",
      "fr": "Dictionnaire avec une étymologie approfondie",
      "de": "Wörterbuch mit tiefgehender Etymologie",
      "pt": "Dicionário com etimologia profunda",
      "it": "Dizionario con etimologia approfondita",
      "nl": "Woordenboek met diepgaande etymologie",
      "ru": "Словарь с глубокой этимологией",
      "ja": "語源をたどる辞書",
      "zh-Hans": "带有深度词源的词典",
      "ko": "깊이 있는 어원 사전",
      "ar": "قاموس مع أصول متعمقة للكلمات"
    },
    "web.title": {
      "en": "Wordroot — dictionary + etymology",
      "es": "Wordroot — diccionario + etimología",
      "fr": "Wordroot — dictionnaire + étymologie",
      "de": "Wordroot — Wörterbuch + Etymologie",
      "pt": "Wordroot — dicionário + etimologia",
      "it": "Wordroot — dizionario + etimologia",
      "nl": "Wordroot — woordenboek + etymologie",
      "ru": "Wordroot — словарь + этимология",
      "ja": "Wordroot — 辞書 + 語源",
      "zh-Hans": "Wordroot — 词典 + 词源",
      "ko": "Wordroot — 사전 + 어원",
      "ar": "Wordroot — قاموس + علم أصل الكلمات"
    },
    "ui.language": {
      "en": "Language",
      "es": "Idioma",
      "fr": "Langue",
      "de": "Sprache",
      "pt": "Idioma",
      "it": "Lingua",
      "nl": "Taal",
      "ru": "Язык",
      "ja": "言語",
      "zh-Hans": "语言",
      "ko": "언어",
      "ar": "اللغة"
    },
    "ui.interfaceLanguage": {
      "en": "Interface language",
      "es": "Idioma de la interfaz",
      "fr": "Langue de l’interface",
      "de": "Sprache der Oberfläche",
      "pt": "Idioma da interface",
      "it": "Lingua dell’interfaccia",
      "nl": "Taal van de interface",
      "ru": "Язык интерфейса",
      "ja": "表示言語",
      "zh-Hans": "界面语言",
      "ko": "인터페이스 언어",
      "ar": "لغة الواجهة"
    },
    "ui.wordLanguage": {
      "en": "Word language",
      "es": "Idioma de la palabra",
      "fr": "Langue du mot",
      "de": "Sprache des Wortes",
      "pt": "Idioma da palavra",
      "it": "Lingua della parola",
      "nl": "Taal van het woord",
      "ru": "Язык слова",
      "ja": "単語の言語",
      "zh-Hans": "词条语言",
      "ko": "단어 언어",
      "ar": "لغة الكلمة"
    },
    "ui.searchPlaceholder": {
      "en": "Look up a word",
      "es": "Busca una palabra",
      "fr": "Rechercher un mot",
      "de": "Ein Wort nachschlagen",
      "pt": "Procurar uma palavra",
      "it": "Cerca una parola",
      "nl": "Zoek een woord",
      "ru": "Найдите слово",
      "ja": "単語を調べる",
      "zh-Hans": "查一个词",
      "ko": "단어 검색",
      "ar": "ابحث عن كلمة"
    },
    "ui.wotd": {
      "en": "Word of the day",
      "es": "Palabra del día",
      "fr": "Mot du jour",
      "de": "Wort des Tages",
      "pt": "Palavra do dia",
      "it": "Parola del giorno",
      "nl": "Woord van de dag",
      "ru": "Слово дня",
      "ja": "今日の単語",
      "zh-Hans": "每日一词",
      "ko": "오늘의 단어",
      "ar": "كلمة اليوم"
    },
    "ui.wotdWord": {
      "en": "Word of the day: {word}",
      "es": "Palabra del día: {word}",
      "fr": "Mot du jour : {word}",
      "de": "Wort des Tages: {word}",
      "pt": "Palavra do dia: {word}",
      "it": "Parola del giorno: {word}",
      "nl": "Woord van de dag: {word}",
      "ru": "Слово дня: {word}",
      "ja": "今日の単語: {word}",
      "zh-Hans": "每日一词：{word}",
      "ko": "오늘의 단어: {word}",
      "ar": "كلمة اليوم: {word}"
    },
    "ui.origin": {
      "en": "Origin",
      "es": "Origen",
      "fr": "Origine",
      "de": "Herkunft",
      "pt": "Origem",
      "it": "Origine",
      "nl": "Herkomst",
      "ru": "Происхождение",
      "ja": "語源",
      "zh-Hans": "词源",
      "ko": "어원",
      "ar": "الأصل"
    },
    "ui.lookingUp": {
      "en": "Looking up…",
      "es": "Buscando…",
      "fr": "Recherche…",
      "de": "Wird nachgeschlagen…",
      "pt": "A procurar…",
      "it": "Ricerca in corso…",
      "nl": "Bezig met opzoeken…",
      "ru": "Ищем…",
      "ja": "検索中…",
      "zh-Hans": "查询中…",
      "ko": "찾는 중…",
      "ar": "جارٍ البحث…"
    },
    "ui.noDefinition": {
      "en": "No definition found.",
      "es": "No se encontró ninguna definición.",
      "fr": "Aucune définition trouvée.",
      "de": "Keine Definition gefunden.",
      "pt": "Nenhuma definição encontrada.",
      "it": "Nessuna definizione trovata.",
      "nl": "Geen definitie gevonden.",
      "ru": "Определение не найдено.",
      "ja": "定義が見つかりませんでした。",
      "zh-Hans": "未找到释义。",
      "ko": "뜻풀이를 찾지 못했습니다.",
      "ar": "لم يُعثر على تعريف."
    },
    "ui.nothingFoundFor": {
      "en": "Nothing found for “{word}”.",
      "es": "No se encontró nada para «{word}».",
      "fr": "Aucun résultat pour « {word} ».",
      "de": "Nichts gefunden für „{word}“.",
      "pt": "Nada encontrado para «{word}».",
      "it": "Nessun risultato per «{word}».",
      "nl": "Niets gevonden voor ‘{word}’.",
      "ru": "Ничего не найдено по запросу «{word}».",
      "ja": "「{word}」は見つかりませんでした。",
      "zh-Hans": "未找到“{word}”。",
      "ko": "“{word}”에 대한 결과가 없습니다.",
      "ar": "لا نتائج لـ «{word}»."
    },
    "ui.nothingFound": {
      "en": "Nothing found.",
      "es": "No se encontró nada.",
      "fr": "Aucun résultat.",
      "de": "Nichts gefunden.",
      "pt": "Nada encontrado.",
      "it": "Nessun risultato.",
      "nl": "Niets gevonden.",
      "ru": "Ничего не найдено.",
      "ja": "見つかりませんでした。",
      "zh-Hans": "未找到结果。",
      "ko": "결과가 없습니다.",
      "ar": "لا نتائج."
    },
    "ui.networkError": {
      "en": "Network error — try again.",
      "es": "Error de red: inténtalo de nuevo.",
      "fr": "Erreur réseau — réessayez.",
      "de": "Netzwerkfehler – bitte erneut versuchen.",
      "pt": "Erro de rede — tente novamente.",
      "it": "Errore di rete — riprova.",
      "nl": "Netwerkfout — probeer het opnieuw.",
      "ru": "Ошибка сети — попробуйте ещё раз.",
      "ja": "ネットワークエラー — もう一度お試しください。",
      "zh-Hans": "网络错误 — 请重试。",
      "ko": "네트워크 오류 — 다시 시도해 주세요.",
      "ar": "خطأ في الشبكة — حاول مرة أخرى."
    },
    "ui.offline": {
      "en": "Couldn’t reach Wiktionary. Check your connection.",
      "es": "No se pudo conectar con Wiktionary. Comprueba tu conexión.",
      "fr": "Impossible de joindre le Wiktionnaire. Vérifiez votre connexion.",
      "de": "Wiktionary ist nicht erreichbar. Prüfe deine Verbindung.",
      "pt": "Não foi possível contactar o Wiktionary. Verifique a sua ligação.",
      "it": "Impossibile raggiungere il Wikizionario. Controlla la connessione.",
      "nl": "Wiktionary is niet bereikbaar. Controleer je verbinding.",
      "ru": "Не удалось связаться с Викисловарём. Проверьте подключение.",
      "ja": "Wiktionary に接続できませんでした。接続を確認してください。",
      "zh-Hans": "无法连接维基词典。请检查网络连接。",
      "ko": "위키낱말사전에 연결할 수 없습니다. 연결을 확인해 주세요.",
      "ar": "تعذّر الوصول إلى ويكاموس. تحقّق من اتصالك."
    },
    "ui.attribution": {
      "en": "Definitions and etymologies from Wiktionary (CC BY-SA 4.0)",
      "es": "Definiciones y etimologías de Wiktionary (CC BY-SA 4.0)",
      "fr": "Définitions et étymologies issues du Wiktionnaire (CC BY-SA 4.0)",
      "de": "Definitionen und Etymologien aus dem Wiktionary (CC BY-SA 4.0)",
      "pt": "Definições e etimologias do Wiktionary (CC BY-SA 4.0)",
      "it": "Definizioni ed etimologie dal Wikizionario (CC BY-SA 4.0)",
      "nl": "Definities en etymologieën van Wiktionary (CC BY-SA 4.0)",
      "ru": "Определения и этимологии из Викисловаря (CC BY-SA 4.0)",
      "ja": "定義と語源は Wiktionary より（CC BY-SA 4.0）",
      "zh-Hans": "释义与词源来自维基词典（CC BY-SA 4.0）",
      "ko": "뜻풀이와 어원 출처: 위키낱말사전 (CC BY-SA 4.0)",
      "ar": "التعريفات وأصول الكلمات من ويكاموس (CC BY-SA 4.0)"
    },
    "ui.alsoOnApple": {
      "en": "Also on iPhone and Mac as Wordroot.",
      "es": "También en iPhone y Mac como Wordroot.",
      "fr": "Également sur iPhone et Mac sous le nom Wordroot.",
      "de": "Auch für iPhone und Mac als Wordroot.",
      "pt": "Também no iPhone e no Mac como Wordroot.",
      "it": "Disponibile anche su iPhone e Mac come Wordroot.",
      "nl": "Ook op iPhone en Mac als Wordroot.",
      "ru": "Также на iPhone и Mac под именем Wordroot.",
      "ja": "iPhone と Mac でも Wordroot として利用できます。",
      "zh-Hans": "iPhone 和 Mac 上也有 Wordroot。",
      "ko": "iPhone과 Mac에서도 Wordroot로 이용할 수 있습니다.",
      "ar": "متوفر أيضاً على iPhone وMac باسم Wordroot."
    },
    "ui.wiktionary": {
      "en": "Wiktionary",
      "es": "Wikcionario",
      "fr": "Wiktionnaire",
      "de": "Wiktionary",
      "pt": "Wikcionário",
      "it": "Wikizionario",
      "nl": "WikiWoordenboek",
      "ru": "Викисловарь",
      "ja": "ウィクショナリー",
      "zh-Hans": "维基词典",
      "ko": "위키낱말사전",
      "ar": "ويكاموس"
    },
    "ui.privacy": {
      "en": "Privacy",
      "es": "Privacidad",
      "fr": "Confidentialité",
      "de": "Datenschutz",
      "pt": "Privacidade",
      "it": "Privacy",
      "nl": "Privacy",
      "ru": "Конфиденциальность",
      "ja": "プライバシー",
      "zh-Hans": "隐私",
      "ko": "개인정보",
      "ar": "الخصوصية"
    },
    "ui.systemDefault": {
      "en": "System default",
      "es": "Predeterminado del sistema",
      "fr": "Réglage du système",
      "de": "Systemstandard",
      "pt": "Predefinição do sistema",
      "it": "Predefinita di sistema",
      "nl": "Systeemstandaard",
      "ru": "Как в системе",
      "ja": "システムに合わせる",
      "zh-Hans": "跟随系统",
      "ko": "시스템 기본값",
      "ar": "افتراضي النظام"
    },
    "ui.settings": {
      "en": "Settings",
      "es": "Ajustes",
      "fr": "Réglages",
      "de": "Einstellungen",
      "pt": "Definições",
      "it": "Impostazioni",
      "nl": "Instellingen",
      "ru": "Настройки",
      "ja": "設定",
      "zh-Hans": "设置",
      "ko": "설정",
      "ar": "الإعدادات"
    },
    "ui.done": {
      "en": "Done",
      "es": "Listo",
      "fr": "Terminé",
      "de": "Fertig",
      "pt": "Concluído",
      "it": "Fine",
      "nl": "Gereed",
      "ru": "Готово",
      "ja": "完了",
      "zh-Hans": "完成",
      "ko": "완료",
      "ar": "تم"
    },
    "rel.inherited": {
      "en": "inherited",
      "es": "heredado",
      "fr": "hérité",
      "de": "ererbt",
      "pt": "herdado",
      "it": "ereditato",
      "nl": "geërfd",
      "ru": "унаследовано",
      "ja": "継承",
      "zh-Hans": "继承",
      "ko": "계승",
      "ar": "موروثة"
    },
    "rel.derived": {
      "en": "derived",
      "es": "derivado",
      "fr": "dérivé",
      "de": "abgeleitet",
      "pt": "derivado",
      "it": "derivato",
      "nl": "afgeleid",
      "ru": "производное",
      "ja": "派生",
      "zh-Hans": "派生",
      "ko": "파생",
      "ar": "مشتقة"
    },
    "rel.borrowed": {
      "en": "borrowed",
      "es": "prestado",
      "fr": "emprunté",
      "de": "entlehnt",
      "pt": "emprestado",
      "it": "prestito",
      "nl": "ontleend",
      "ru": "заимствовано",
      "ja": "借用",
      "zh-Hans": "借入",
      "ko": "차용",
      "ar": "مستعارة"
    },
    "privacy.title": {
      "en": "Privacy — Wordroot",
      "es": "Privacidad — Wordroot",
      "fr": "Confidentialité — Wordroot",
      "de": "Datenschutz — Wordroot",
      "pt": "Privacidade — Wordroot",
      "it": "Privacy — Wordroot",
      "nl": "Privacy — Wordroot",
      "ru": "Конфиденциальность — Wordroot",
      "ja": "プライバシー — Wordroot",
      "zh-Hans": "隐私 — Wordroot",
      "ko": "개인정보 — Wordroot",
      "ar": "الخصوصية — Wordroot"
    },
    "privacy.heading": {
      "en": "Privacy Policy",
      "es": "Política de privacidad",
      "fr": "Politique de confidentialité",
      "de": "Datenschutzerklärung",
      "pt": "Política de privacidade",
      "it": "Informativa sulla privacy",
      "nl": "Privacybeleid",
      "ru": "Политика конфиденциальности",
      "ja": "プライバシーポリシー",
      "zh-Hans": "隐私政策",
      "ko": "개인정보 처리방침",
      "ar": "سياسة الخصوصية"
    },
    "privacy.lastUpdated": {
      "en": "Last updated {date}",
      "es": "Última actualización: {date}",
      "fr": "Dernière mise à jour : {date}",
      "de": "Zuletzt aktualisiert: {date}",
      "pt": "Última atualização: {date}",
      "it": "Ultimo aggiornamento: {date}",
      "nl": "Laatst bijgewerkt: {date}",
      "ru": "Последнее обновление: {date}",
      "ja": "最終更新: {date}",
      "zh-Hans": "最后更新：{date}",
      "ko": "최종 업데이트: {date}",
      "ar": "آخر تحديث: {date}"
    },
    "privacy.collect.h": {
      "en": "What we collect",
      "es": "Qué recopilamos",
      "fr": "Ce que nous collectons",
      "de": "Was wir erheben",
      "pt": "O que recolhemos",
      "it": "Cosa raccogliamo",
      "nl": "Wat we verzamelen",
      "ru": "Что мы собираем",
      "ja": "収集する情報",
      "zh-Hans": "我们收集什么",
      "ko": "수집하는 정보",
      "ar": "ما الذي نجمعه"
    },
    "privacy.collect.p": {
      "en": "Nothing. The app and website have no accounts, no sign-in, no analytics, and no advertising. We do not collect, store, or transmit any personal information, and nothing you type is sent to us.",
      "es": "Nada. La app y el sitio web no tienen cuentas, ni inicio de sesión, ni analíticas, ni publicidad. No recopilamos, almacenamos ni transmitimos ninguna información personal, y nada de lo que escribes se nos envía.",
      "fr": "Rien. L’application et le site n’ont ni comptes, ni connexion, ni analytique, ni publicité. Nous ne collectons, ne stockons et ne transmettons aucune information personnelle, et rien de ce que vous saisissez ne nous est envoyé.",
      "de": "Nichts. App und Website haben keine Konten, keine Anmeldung, keine Analyse und keine Werbung. Wir erheben, speichern und übertragen keine personenbezogenen Daten, und nichts, was du eingibst, wird an uns gesendet.",
      "pt": "Nada. A aplicação e o site não têm contas, início de sessão, análises nem publicidade. Não recolhemos, armazenamos nem transmitimos qualquer informação pessoal, e nada do que escreve nos é enviado.",
      "it": "Niente. L’app e il sito non hanno account, accessi, analytics o pubblicità. Non raccogliamo, conserviamo né trasmettiamo alcuna informazione personale, e nulla di ciò che digiti ci viene inviato.",
      "nl": "Niets. De app en de website hebben geen accounts, geen inloggen, geen analytics en geen advertenties. We verzamelen, bewaren en versturen geen persoonlijke gegevens, en niets van wat je typt wordt naar ons gestuurd.",
      "ru": "Ничего. В приложении и на сайте нет аккаунтов, входа, аналитики и рекламы. Мы не собираем, не храним и не передаём никакой личной информации, и ничего из того, что вы вводите, к нам не попадает.",
      "ja": "何も収集しません。アプリとウェブサイトにはアカウント、ログイン、アナリティクス、広告がありません。個人情報を収集・保存・送信することはなく、入力した内容が当方に送られることもありません。",
      "zh-Hans": "什么都不收集。应用和网站没有账号、没有登录、没有分析统计、没有广告。我们不收集、不存储、不传输任何个人信息，你输入的内容也不会发送给我们。",
      "ko": "아무것도 수집하지 않습니다. 앱과 웹사이트에는 계정, 로그인, 분석 도구, 광고가 없습니다. 어떠한 개인정보도 수집·저장·전송하지 않으며, 입력한 내용은 저희에게 전송되지 않습니다.",
      "ar": "لا شيء. لا يحتوي التطبيق والموقع على حسابات أو تسجيل دخول أو تحليلات أو إعلانات. نحن لا نجمع أي معلومات شخصية ولا نخزّنها ولا ننقلها، ولا يُرسل إلينا أي شيء تكتبه."
    },
    "privacy.lookups.h": {
      "en": "Word lookups",
      "es": "Búsquedas de palabras",
      "fr": "Recherches de mots",
      "de": "Wortsuchen",
      "pt": "Pesquisas de palavras",
      "it": "Ricerche di parole",
      "nl": "Woorden opzoeken",
      "ru": "Поиск слов",
      "ja": "単語の検索",
      "zh-Hans": "单词查询",
      "ko": "단어 검색",
      "ar": "عمليات البحث عن الكلمات"
    },
    "privacy.lookups.p": {
      "en": "When you look up a word, the app requests that word’s page directly from the public {wiktionary} API operated by the Wikimedia Foundation. That request is not routed through any server we control. Wikimedia’s handling of such requests is covered by their {policy}.",
      "es": "Cuando buscas una palabra, la app solicita la página de esa palabra directamente a la API pública de {wiktionary}, operada por la Fundación Wikimedia. Esa solicitud no pasa por ningún servidor bajo nuestro control. El tratamiento que Wikimedia hace de esas solicitudes se rige por su {policy}.",
      "fr": "Lorsque vous recherchez un mot, l’application demande la page de ce mot directement à l’API publique du {wiktionary}, exploitée par la Wikimedia Foundation. Cette requête ne transite par aucun serveur que nous contrôlons. Le traitement de ces requêtes par Wikimedia relève de sa {policy}.",
      "de": "Wenn du ein Wort nachschlägst, fragt die App die Seite dieses Wortes direkt bei der öffentlichen API von {wiktionary} an, die von der Wikimedia Foundation betrieben wird. Diese Anfrage läuft über keinen Server, den wir kontrollieren. Wie Wikimedia solche Anfragen behandelt, regelt deren {policy}.",
      "pt": "Quando procura uma palavra, a aplicação pede a página dessa palavra diretamente à API pública do {wiktionary}, operada pela Wikimedia Foundation. Esse pedido não passa por nenhum servidor que controlemos. O tratamento desses pedidos pela Wikimedia é regido pela sua {policy}.",
      "it": "Quando cerchi una parola, l’app richiede la pagina di quella parola direttamente all’API pubblica del {wiktionary}, gestita dalla Wikimedia Foundation. Quella richiesta non passa da alcun server sotto il nostro controllo. Il trattamento di tali richieste da parte di Wikimedia è regolato dalla sua {policy}.",
      "nl": "Wanneer je een woord opzoekt, vraagt de app de pagina van dat woord rechtstreeks op bij de openbare API van {wiktionary}, beheerd door de Wikimedia Foundation. Dat verzoek loopt niet via een server die wij beheren. Hoe Wikimedia zulke verzoeken verwerkt, staat in hun {policy}.",
      "ru": "Когда вы ищете слово, приложение запрашивает страницу этого слова напрямую у общедоступного API «{wiktionary}», который работает под управлением Wikimedia Foundation. Этот запрос не проходит ни через один сервер, который мы контролируем. Обработка таких запросов Wikimedia описана в их {policy}.",
      "ja": "単語を調べると、アプリはその単語のページを、ウィキメディア財団が運営する公開 API（{wiktionary}）に直接リクエストします。このリクエストが当方の管理するサーバーを経由することはありません。ウィキメディアによるリクエストの取り扱いは同財団の{policy}に従います。",
      "zh-Hans": "当你查询一个词时，应用会直接向维基媒体基金会运营的 {wiktionary} 公开 API 请求该词的页面。该请求不会经过任何由我们控制的服务器。维基媒体对此类请求的处理适用其{policy}。",
      "ko": "단어를 검색하면 앱은 위키미디어 재단이 운영하는 공개 {wiktionary} API에 해당 단어의 페이지를 직접 요청합니다. 이 요청은 저희가 통제하는 어떤 서버도 거치지 않습니다. 위키미디어의 요청 처리 방식은 해당 재단의 {policy}을 따릅니다.",
      "ar": "عند البحث عن كلمة، يطلب التطبيق صفحة تلك الكلمة مباشرةً من واجهة برمجة التطبيقات العامة لـ{wiktionary} التي تديرها مؤسسة ويكيميديا. لا يمر هذا الطلب عبر أي خادم نتحكم به. تخضع معالجة ويكيميديا لهذه الطلبات لـ{policy} الخاصة بها."
    },
    "privacy.policyLink": {
      "en": "privacy policy",
      "es": "política de privacidad",
      "fr": "politique de confidentialité",
      "de": "Datenschutzerklärung",
      "pt": "política de privacidade",
      "it": "informativa sulla privacy",
      "nl": "privacybeleid",
      "ru": "политике конфиденциальности",
      "ja": "プライバシーポリシー",
      "zh-Hans": "隐私政策",
      "ko": "개인정보 처리방침",
      "ar": "سياسة الخصوصية"
    },
    "privacy.device.h": {
      "en": "Data stored on your device",
      "es": "Datos guardados en tu dispositivo",
      "fr": "Données stockées sur votre appareil",
      "de": "Auf deinem Gerät gespeicherte Daten",
      "pt": "Dados guardados no seu dispositivo",
      "it": "Dati salvati sul tuo dispositivo",
      "nl": "Gegevens op je apparaat",
      "ru": "Данные на вашем устройстве",
      "ja": "端末に保存されるデータ",
      "zh-Hans": "存储在你设备上的数据",
      "ko": "기기에 저장되는 데이터",
      "ar": "البيانات المخزَّنة على جهازك"
    },
    "privacy.device.p": {
      "en": "Your search text while the app is open, plus your interface and word language choices, which are saved locally so the app opens in the same languages next time. Both stay on your device and are never sent to us.",
      "es": "El texto de tu búsqueda mientras la app está abierta, además de tus preferencias de idioma de la interfaz y de la palabra, que se guardan localmente para que la app se abra en los mismos idiomas la próxima vez. Ambos permanecen en tu dispositivo y nunca se nos envían.",
      "fr": "Le texte de votre recherche tant que l’application est ouverte, ainsi que vos choix de langue d’interface et de langue des mots, enregistrés localement afin que l’application s’ouvre dans les mêmes langues la fois suivante. Les deux restent sur votre appareil et ne nous sont jamais envoyés.",
      "de": "Dein Suchtext, solange die App geöffnet ist, sowie deine Einstellungen für Oberflächen- und Wortsprache, die lokal gespeichert werden, damit die App beim nächsten Mal in denselben Sprachen startet. Beides bleibt auf deinem Gerät und wird nie an uns gesendet.",
      "pt": "O texto da sua pesquisa enquanto a aplicação está aberta, e as suas escolhas de idioma da interface e da palavra, guardadas localmente para que a aplicação abra nos mesmos idiomas da próxima vez. Ambos ficam no seu dispositivo e nunca nos são enviados.",
      "it": "Il testo della tua ricerca finché l’app è aperta, più le tue scelte di lingua dell’interfaccia e delle parole, salvate localmente così che l’app si apra nelle stesse lingue la volta successiva. Entrambi restano sul tuo dispositivo e non ci vengono mai inviati.",
      "nl": "De tekst van je zoekopdracht zolang de app open is, plus je keuzes voor interfacetaal en woordtaal, die lokaal worden bewaard zodat de app de volgende keer in dezelfde talen opent. Beide blijven op je apparaat en worden nooit naar ons gestuurd.",
      "ru": "Текст вашего запроса, пока приложение открыто, и выбранные вами язык интерфейса и язык слов — они сохраняются локально, чтобы в следующий раз приложение открылось на тех же языках. И то и другое остаётся на вашем устройстве и никогда к нам не отправляется.",
      "ja": "アプリを開いている間の検索テキストと、表示言語・単語の言語の設定です。設定は次回も同じ言語で開けるようローカルに保存されます。どちらも端末内に留まり、当方に送信されることはありません。",
      "zh-Hans": "应用打开期间的搜索文本，以及你选择的界面语言和词条语言；语言选择会保存在本地，以便下次以相同语言打开。两者都留在你的设备上，绝不会发送给我们。",
      "ko": "앱이 열려 있는 동안의 검색어와, 선택한 인터페이스 언어 및 단어 언어입니다. 언어 설정은 다음에도 같은 언어로 열리도록 기기에 저장됩니다. 둘 다 기기에만 남으며 저희에게 전송되지 않습니다.",
      "ar": "نص بحثك ما دام التطبيق مفتوحاً، إضافةً إلى اختياراتك للغة الواجهة ولغة الكلمة، وتُحفظ محلياً كي يُفتح التطبيق باللغات نفسها في المرة القادمة. يبقى كلاهما على جهازك ولا يُرسل إلينا أبداً."
    },
    "privacy.children.h": {
      "en": "Children",
      "es": "Menores",
      "fr": "Enfants",
      "de": "Kinder",
      "pt": "Crianças",
      "it": "Minori",
      "nl": "Kinderen",
      "ru": "Дети",
      "ja": "お子様について",
      "zh-Hans": "儿童",
      "ko": "아동",
      "ar": "الأطفال"
    },
    "privacy.children.p": {
      "en": "The app is safe for all ages and collects no data from anyone, including children under 13.",
      "es": "La app es segura para todas las edades y no recopila datos de nadie, incluidos los menores de 13 años.",
      "fr": "L’application convient à tous les âges et ne collecte aucune donnée, y compris auprès des enfants de moins de 13 ans.",
      "de": "Die App ist für alle Altersgruppen geeignet und erhebt von niemandem Daten, auch nicht von Kindern unter 13 Jahren.",
      "pt": "A aplicação é segura para todas as idades e não recolhe dados de ninguém, incluindo crianças com menos de 13 anos.",
      "it": "L’app è adatta a tutte le età e non raccoglie dati da nessuno, nemmeno dai minori di 13 anni.",
      "nl": "De app is geschikt voor alle leeftijden en verzamelt van niemand gegevens, ook niet van kinderen onder de 13.",
      "ru": "Приложение подходит для любого возраста и не собирает данные ни у кого, включая детей младше 13 лет.",
      "ja": "本アプリは全年齢に適しており、13 歳未満のお子様を含め、誰からもデータを収集しません。",
      "zh-Hans": "本应用适合所有年龄段，不会收集任何人的数据，包括 13 岁以下的儿童。",
      "ko": "이 앱은 모든 연령대에 안전하며, 13세 미만 아동을 포함해 누구에게서도 데이터를 수집하지 않습니다.",
      "ar": "التطبيق مناسب لجميع الأعمار ولا يجمع أي بيانات من أي شخص، بمن فيهم الأطفال دون سن 13 عاماً."
    },
    "privacy.changes.h": {
      "en": "Changes",
      "es": "Cambios",
      "fr": "Modifications",
      "de": "Änderungen",
      "pt": "Alterações",
      "it": "Modifiche",
      "nl": "Wijzigingen",
      "ru": "Изменения",
      "ja": "変更について",
      "zh-Hans": "变更",
      "ko": "변경 사항",
      "ar": "التغييرات"
    },
    "privacy.changes.p": {
      "en": "If this policy changes, the updated version will be posted at this URL.",
      "es": "Si esta política cambia, la versión actualizada se publicará en esta misma URL.",
      "fr": "Si cette politique change, la version mise à jour sera publiée à cette adresse.",
      "de": "Wenn sich diese Erklärung ändert, wird die aktualisierte Fassung unter dieser URL veröffentlicht.",
      "pt": "Se esta política for alterada, a versão atualizada será publicada neste URL.",
      "it": "Se questa informativa cambia, la versione aggiornata sarà pubblicata a questo indirizzo.",
      "nl": "Als dit beleid verandert, wordt de bijgewerkte versie op deze URL geplaatst.",
      "ru": "Если политика изменится, обновлённая версия будет опубликована по этому адресу.",
      "ja": "本ポリシーが変更された場合、更新版をこの URL に掲載します。",
      "zh-Hans": "若本政策发生变更，更新后的版本将发布在此网址。",
      "ko": "이 방침이 변경되면 업데이트된 내용을 이 URL에 게시합니다.",
      "ar": "في حال تغيّرت هذه السياسة، ستُنشر النسخة المحدَّثة على هذا الرابط."
    },
    "privacy.contact.h": {
      "en": "Contact",
      "es": "Contacto",
      "fr": "Contact",
      "de": "Kontakt",
      "pt": "Contacto",
      "it": "Contatti",
      "nl": "Contact",
      "ru": "Контакты",
      "ja": "お問い合わせ",
      "zh-Hans": "联系方式",
      "ko": "문의",
      "ar": "التواصل"
    },
    "privacy.back": {
      "en": "Back to Wordroot",
      "es": "Volver a Wordroot",
      "fr": "Retour à Wordroot",
      "de": "Zurück zu Wordroot",
      "pt": "Voltar ao Wordroot",
      "it": "Torna a Wordroot",
      "nl": "Terug naar Wordroot",
      "ru": "Назад к Wordroot",
      "ja": "Wordroot に戻る",
      "zh-Hans": "返回 Wordroot",
      "ko": "Wordroot로 돌아가기",
      "ar": "العودة إلى Wordroot"
    },
    "lang.gmw-pro": {
      "en": "Proto-West Germanic",
      "es": "protogermánico occidental",
      "fr": "proto-germanique occidental",
      "de": "Urwestgermanisch",
      "pt": "proto-germânico ocidental",
      "it": "proto-germanico occidentale",
      "nl": "Proto-West-Germaans",
      "ru": "празападногерманский",
      "ja": "西ゲルマン祖語",
      "zh-Hans": "原始西日耳曼语",
      "ko": "서게르만조어",
      "ar": "الجرمانية الغربية البدائية"
    },
    "lang.gem-pro": {
      "en": "Proto-Germanic",
      "es": "protogermánico",
      "fr": "proto-germanique",
      "de": "Urgermanisch",
      "pt": "proto-germânico",
      "it": "proto-germanico",
      "nl": "Proto-Germaans",
      "ru": "прагерманский",
      "ja": "ゲルマン祖語",
      "zh-Hans": "原始日耳曼语",
      "ko": "게르만조어",
      "ar": "الجرمانية البدائية"
    },
    "lang.ine-pro": {
      "en": "Proto-Indo-European",
      "es": "protoindoeuropeo",
      "fr": "indo-européen commun",
      "de": "Urindogermanisch",
      "pt": "proto-indo-europeu",
      "it": "proto-indoeuropeo",
      "nl": "Proto-Indo-Europees",
      "ru": "праиндоевропейский",
      "ja": "印欧祖語",
      "zh-Hans": "原始印欧语",
      "ko": "인도유럽조어",
      "ar": "الهندية الأوروبية البدائية"
    },
    "lang.itc-pro": {
      "en": "Proto-Italic",
      "es": "protoitálico",
      "fr": "proto-italique",
      "de": "Uritalisch",
      "pt": "proto-itálico",
      "it": "proto-italico",
      "nl": "Proto-Italisch",
      "ru": "праиталийский",
      "ja": "イタリック祖語",
      "zh-Hans": "原始意大利语",
      "ko": "이탈리아조어",
      "ar": "الإيطالية البدائية"
    },
    "lang.la-med": {
      "en": "Medieval Latin",
      "es": "latín medieval",
      "fr": "latin médiéval",
      "de": "Mittellatein",
      "pt": "latim medieval",
      "it": "latino medievale",
      "nl": "Middeleeuws Latijn",
      "ru": "средневековая латынь",
      "ja": "中世ラテン語",
      "zh-Hans": "中世纪拉丁语",
      "ko": "중세 라틴어",
      "ar": "اللاتينية الوسيطة"
    },
    "lang.NL.": {
      "en": "New Latin",
      "es": "latín moderno",
      "fr": "latin moderne",
      "de": "Neulatein",
      "pt": "latim moderno",
      "it": "latino moderno",
      "nl": "Nieuwlatijn",
      "ru": "новая латынь",
      "ja": "近代ラテン語",
      "zh-Hans": "新拉丁语",
      "ko": "근대 라틴어",
      "ar": "اللاتينية الحديثة"
    },
    "lang.gkm": {
      "en": "Byzantine Greek",
      "es": "griego bizantino",
      "fr": "grec byzantin",
      "de": "Byzantinisches Griechisch",
      "pt": "grego bizantino",
      "it": "greco bizantino",
      "nl": "Byzantijns Grieks",
      "ru": "византийский греческий",
      "ja": "ビザンチンギリシャ語",
      "zh-Hans": "拜占庭希腊语",
      "ko": "비잔틴 그리스어",
      "ar": "اليونانية البيزنطية"
    }
  },
  "wordLanguages": [
    {
      "code": "en",
      "section": "English",
      "english": "English"
    },
    {
      "code": "es",
      "section": "Spanish",
      "english": "Spanish"
    },
    {
      "code": "fr",
      "section": "French",
      "english": "French"
    },
    {
      "code": "de",
      "section": "German",
      "english": "German"
    },
    {
      "code": "pt",
      "section": "Portuguese",
      "english": "Portuguese"
    },
    {
      "code": "it",
      "section": "Italian",
      "english": "Italian"
    },
    {
      "code": "nl",
      "section": "Dutch",
      "english": "Dutch"
    },
    {
      "code": "ru",
      "section": "Russian",
      "english": "Russian"
    },
    {
      "code": "ja",
      "section": "Japanese",
      "english": "Japanese"
    },
    {
      "code": "zh",
      "section": "Chinese",
      "english": "Chinese"
    },
    {
      "code": "ko",
      "section": "Korean",
      "english": "Korean"
    },
    {
      "code": "ar",
      "section": "Arabic",
      "english": "Arabic"
    },
    {
      "code": "he",
      "section": "Hebrew",
      "english": "Hebrew"
    },
    {
      "code": "fa",
      "section": "Persian",
      "english": "Persian"
    },
    {
      "code": "hi",
      "section": "Hindi",
      "english": "Hindi"
    },
    {
      "code": "tr",
      "section": "Turkish",
      "english": "Turkish"
    },
    {
      "code": "pl",
      "section": "Polish",
      "english": "Polish"
    },
    {
      "code": "sv",
      "section": "Swedish",
      "english": "Swedish"
    },
    {
      "code": "da",
      "section": "Danish",
      "english": "Danish"
    },
    {
      "code": "no",
      "section": "Norwegian",
      "english": "Norwegian"
    },
    {
      "code": "fi",
      "section": "Finnish",
      "english": "Finnish"
    },
    {
      "code": "is",
      "section": "Icelandic",
      "english": "Icelandic"
    },
    {
      "code": "ga",
      "section": "Irish",
      "english": "Irish"
    },
    {
      "code": "cy",
      "section": "Welsh",
      "english": "Welsh"
    },
    {
      "code": "el",
      "section": "Greek",
      "english": "Greek"
    },
    {
      "code": "la",
      "section": "Latin",
      "english": "Latin"
    },
    {
      "code": "grc",
      "section": "Ancient Greek",
      "english": "Ancient Greek"
    },
    {
      "code": "sa",
      "section": "Sanskrit",
      "english": "Sanskrit"
    },
    {
      "code": "ang",
      "section": "Old English",
      "english": "Old English"
    },
    {
      "code": "non",
      "section": "Old Norse",
      "english": "Old Norse"
    }
  ],
  "ancestorLanguages": {
    "enm": "Middle English",
    "ang": "Old English",
    "gmw-pro": "Proto-West Germanic",
    "gem-pro": "Proto-Germanic",
    "ine-pro": "Proto-Indo-European",
    "la": "Latin",
    "la-med": "Medieval Latin",
    "NL.": "New Latin",
    "grc": "Ancient Greek",
    "gkm": "Byzantine Greek",
    "fro": "Old French",
    "fr": "French",
    "frm": "Middle French",
    "non": "Old Norse",
    "nl": "Dutch",
    "de": "German",
    "es": "Spanish",
    "it": "Italian",
    "itc-pro": "Proto-Italic",
    "ar": "Arabic",
    "sa": "Sanskrit"
  },
  "wordsOfTheDay": {
    "en": [
      "water",
      "mother",
      "star",
      "night",
      "heart",
      "fire",
      "wind",
      "tooth",
      "name",
      "wolf",
      "snow",
      "honey",
      "door",
      "ear",
      "foot",
      "knee",
      "sun",
      "moon",
      "salt",
      "seed",
      "yoke",
      "new",
      "red",
      "three",
      "brother"
    ],
    "es": [
      "agua",
      "madre",
      "noche",
      "corazón",
      "fuego",
      "luna",
      "sol",
      "mano",
      "nombre",
      "lobo",
      "sal",
      "puerta",
      "pie",
      "diente"
    ],
    "fr": [
      "eau",
      "mère",
      "nuit",
      "cœur",
      "feu",
      "lune",
      "soleil",
      "main",
      "nom",
      "loup",
      "sel",
      "porte",
      "pied",
      "dent"
    ],
    "de": [
      "Wasser",
      "Mutter",
      "Nacht",
      "Herz",
      "Feuer",
      "Mond",
      "Sonne",
      "Hand",
      "Name",
      "Wolf",
      "Salz",
      "Tür",
      "Fuß",
      "Zahn"
    ],
    "pt": [
      "água",
      "mãe",
      "noite",
      "coração",
      "fogo",
      "lua",
      "sol",
      "mão",
      "nome",
      "lobo",
      "sal",
      "porta",
      "pé",
      "dente"
    ],
    "it": [
      "acqua",
      "madre",
      "notte",
      "cuore",
      "fuoco",
      "luna",
      "sole",
      "mano",
      "nome",
      "lupo",
      "sale",
      "porta",
      "piede",
      "dente"
    ],
    "nl": [
      "water",
      "moeder",
      "nacht",
      "hart",
      "vuur",
      "maan",
      "zon",
      "hand",
      "naam",
      "wolf",
      "zout",
      "deur",
      "voet",
      "tand"
    ],
    "ru": [
      "вода",
      "мать",
      "ночь",
      "сердце",
      "огонь",
      "луна",
      "солнце",
      "рука",
      "имя",
      "волк",
      "соль",
      "дверь",
      "нога",
      "зуб"
    ],
    "ja": [
      "水",
      "母",
      "夜",
      "心",
      "火",
      "月",
      "日",
      "手",
      "名",
      "狼",
      "塩",
      "門",
      "足",
      "歯"
    ],
    "zh": [
      "水",
      "母",
      "夜",
      "心",
      "火",
      "月",
      "日",
      "手",
      "名",
      "狼",
      "盐",
      "门",
      "足",
      "齿"
    ],
    "ko": [
      "물",
      "어머니",
      "밤",
      "마음",
      "불",
      "달",
      "해",
      "손",
      "이름",
      "늑대",
      "소금",
      "문",
      "발",
      "이"
    ],
    "ar": [
      "ماء",
      "أم",
      "ليل",
      "قلب",
      "نار",
      "قمر",
      "شمس",
      "يد",
      "اسم",
      "ذئب",
      "ملح",
      "باب",
      "رجل",
      "سن"
    ],
    "la": [
      "aqua",
      "mater",
      "nox",
      "cor",
      "ignis",
      "luna",
      "sol",
      "manus",
      "nomen",
      "lupus",
      "sal",
      "porta",
      "pes",
      "dens"
    ],
    "grc": [
      "ὕδωρ",
      "μήτηρ",
      "νύξ",
      "καρδία",
      "πῦρ",
      "σελήνη",
      "ἥλιος",
      "χείρ",
      "ὄνομα",
      "λύκος",
      "ἅλς",
      "θύρα",
      "πούς",
      "ὀδούς"
    ]
  }
};

  var STORAGE_KEY = 'wordroot.uiLang';
  var codes = DATA.locales.map(function (l) { return l.code; });

  // Chinese is offered in Simplified only, so every zh variant — zh, zh-CN, zh-Hant-TW —
  // negotiates to it rather than falling through to English.
  function normalize(tag) {
    if (!tag) return null;
    tag = String(tag).replace(/_/g, '-');
    if (/^zh\b/i.test(tag)) return codes.indexOf('zh-Hans') >= 0 ? 'zh-Hans' : null;
    var parts = tag.split('-');
    while (parts.length) {
      var candidate = parts.join('-');
      for (var i = 0; i < codes.length; i++) {
        if (codes[i].toLowerCase() === candidate.toLowerCase()) return codes[i];
      }
      parts.pop();
    }
    return null;
  }

  function stored(key) {
    try { return localStorage.getItem(key); } catch (e) { return null; }  // Safari private mode throws
  }

  function negotiate() {
    var params = new URLSearchParams(location.search);
    var wanted = [params.get('lang'), stored(STORAGE_KEY)]
      .concat(navigator.languages || [navigator.language]);
    for (var i = 0; i < wanted.length; i++) {
      var hit = normalize(wanted[i]);
      if (hit) return hit;
    }
    return 'en';
  }

  var locale = negotiate();
  var meta = DATA.locales.filter(function (l) { return l.code === locale; })[0];

  var displayNames = null;
  try {
    displayNames = new Intl.DisplayNames([locale, 'en'], { type: 'language' });
  } catch (e) { /* pre-2021 browsers: fall back to the English table below */ }

  var i18n = {
    locale: locale,
    dir: (meta && meta.dir) || 'ltr',
    locales: DATA.locales,
    wordLanguages: DATA.wordLanguages || [],
    wordsOfTheDay: DATA.wordsOfTheDay || {},

    /**
     * Landing-page hero wall, meanings already resolved to this locale. The headword and its
     * source form are proper forms and stay as they are.
     */
    wall: (DATA.wall || []).map(function (e) {
      return { word: e.word, form: e.form, meaning: e.meaning[locale] || e.meaning.en };
    }),

    /** Translate `key`, substituting {name} placeholders from `vars`. */
    t: function (key, vars) {
      var row = DATA.strings[key];
      var s = (row && (row[locale] || row.en)) || key;
      if (!vars) return s;
      return s.replace(/\{(\w+)\}/g, function (m, name) {
        return Object.prototype.hasOwnProperty.call(vars, name) ? vars[name] : m;
      });
    },

    /**
     * Localized name for a language code from a Wiktionary etymology template.
     * Hand translations win, then CLDR, then the English table, then the raw code —
     * so an unrecognized code still renders as itself rather than as an empty cell.
     */
    languageName: function (code) {
      if (!code) return '';
      if (DATA.strings['lang.' + code]) return i18n.t('lang.' + code);
      if (displayNames) {
        try {
          var name = displayNames.of(code);
          if (name && name !== code) return name;
        } catch (e) { /* not a well-formed BCP 47 tag, e.g. "NL." */ }
      }
      return (DATA.ancestorLanguages || {})[code] || code;
    },

    /** Persist a new interface language and reload so every string re-renders. */
    setLocale: function (code) {
      if (!normalize(code)) return;
      try { localStorage.setItem(STORAGE_KEY, code); } catch (e) { /* storage disabled */ }
      var url = new URL(location.href);
      url.searchParams.delete('lang');  // the stored choice is now authoritative
      location.replace(url.toString());
    },

    /** Point <html lang>/<html dir> at the negotiated locale. Safe to call before <body>. */
    applyDocumentLanguage: function () {
      document.documentElement.lang = locale;
      document.documentElement.dir = i18n.dir;
    },

    /** <select> of interface languages, wired to setLocale. */
    localePicker: function (label) {
      var sel = document.createElement('select');
      sel.setAttribute('aria-label', label);
      DATA.locales.forEach(function (l) {
        var opt = document.createElement('option');
        opt.value = l.code;
        opt.textContent = l.endonym;
        opt.lang = l.code;
        if (l.code === locale) opt.selected = true;
        sel.appendChild(opt);
      });
      sel.addEventListener('change', function () { i18n.setLocale(sel.value); });
      return sel;
    },
  };

  window.i18n = i18n;
})();
